// Code generated by "go generate"; DO NOT EDIT.

package semantic

import (
	"fmt"

	"github.com/masterbelt/masterbelt/pkg/masterbelt/diagnostic"
)

const (
	CodeConstantOverflow     diagnostic.Code = "masterbelt.semantic.constant_overflow"
	CodeCyclicReference      diagnostic.Code = "masterbelt.semantic.cyclic_reference"
	CodeDuplicateDeclaration diagnostic.Code = "masterbelt.semantic.duplicate_declaration"
	CodeUndefinedName        diagnostic.Code = "masterbelt.semantic.undefined_name"
	CodeUnknownType          diagnostic.Code = "masterbelt.semantic.unknown_type"
)

func newConstantOverflowDiagnostic(offset int, width int, value string, typ string) diagnostic.Diagnostic {
	fields := map[string]fmt.Stringer{
		"value": diagnostic.Str(value),
		"typ":   diagnostic.Str(typ),
	}
	return diagnostic.Diagnostic{
		Severity: diagnostic.Error,
		Code:     CodeConstantOverflow,
		Message:  diagnostic.Render(diagnostic.DefaultLocale, CodeConstantOverflow, fields),
		Fields:   fields,
		Offset:   offset,
		Width:    width,
	}
}

func newCyclicReferenceDiagnostic(offset int, width int, name string) diagnostic.Diagnostic {
	fields := map[string]fmt.Stringer{
		"name": diagnostic.Str(name),
	}
	return diagnostic.Diagnostic{
		Severity: diagnostic.Error,
		Code:     CodeCyclicReference,
		Message:  diagnostic.Render(diagnostic.DefaultLocale, CodeCyclicReference, fields),
		Fields:   fields,
		Offset:   offset,
		Width:    width,
	}
}

func newDuplicateDeclarationDiagnostic(offset int, width int, name string) diagnostic.Diagnostic {
	fields := map[string]fmt.Stringer{
		"name": diagnostic.Str(name),
	}
	return diagnostic.Diagnostic{
		Severity: diagnostic.Error,
		Code:     CodeDuplicateDeclaration,
		Message:  diagnostic.Render(diagnostic.DefaultLocale, CodeDuplicateDeclaration, fields),
		Fields:   fields,
		Offset:   offset,
		Width:    width,
	}
}

func newUndefinedNameDiagnostic(offset int, width int, name string) diagnostic.Diagnostic {
	fields := map[string]fmt.Stringer{
		"name": diagnostic.Str(name),
	}
	return diagnostic.Diagnostic{
		Severity: diagnostic.Error,
		Code:     CodeUndefinedName,
		Message:  diagnostic.Render(diagnostic.DefaultLocale, CodeUndefinedName, fields),
		Fields:   fields,
		Offset:   offset,
		Width:    width,
	}
}

func newUnknownTypeDiagnostic(offset int, width int, name string) diagnostic.Diagnostic {
	fields := map[string]fmt.Stringer{
		"name": diagnostic.Str(name),
	}
	return diagnostic.Diagnostic{
		Severity: diagnostic.Error,
		Code:     CodeUnknownType,
		Message:  diagnostic.Render(diagnostic.DefaultLocale, CodeUnknownType, fields),
		Fields:   fields,
		Offset:   offset,
		Width:    width,
	}
}
