// Code generated by "go generate"; DO NOT EDIT.

package semantic

import (
	"fmt"

	"github.com/masterbelt/masterbelt/pkg/diagnostic"
)

const (
	CodeAmbiguousImport       diagnostic.Code = "masterbelt.semantic.ambiguous_import"
	CodeAmbiguousOverload     diagnostic.Code = "masterbelt.semantic.ambiguous_overload"
	CodeAssertionFailed       diagnostic.Code = "masterbelt.semantic.assertion_failed"
	CodeAssertionNotBool      diagnostic.Code = "masterbelt.semantic.assertion_not_bool"
	CodeAssertionNotConstant  diagnostic.Code = "masterbelt.semantic.assertion_not_constant"
	CodeConstantOverflow      diagnostic.Code = "masterbelt.semantic.constant_overflow"
	CodeCyclicModule          diagnostic.Code = "masterbelt.semantic.cyclic_module"
	CodeCyclicReference       diagnostic.Code = "masterbelt.semantic.cyclic_reference"
	CodeDivisionByZero        diagnostic.Code = "masterbelt.semantic.division_by_zero"
	CodeDuplicateDeclaration  diagnostic.Code = "masterbelt.semantic.duplicate_declaration"
	CodeDuplicateOverload     diagnostic.Code = "masterbelt.semantic.duplicate_overload"
	CodeInvalidOperation      diagnostic.Code = "masterbelt.semantic.invalid_operation"
	CodeLambdaArityMismatch   diagnostic.Code = "masterbelt.semantic.lambda_arity_mismatch"
	CodeMissingField          diagnostic.Code = "masterbelt.semantic.missing_field"
	CodeNoMatchingOverload    diagnostic.Code = "masterbelt.semantic.no_matching_overload"
	CodeNotARecord            diagnostic.Code = "masterbelt.semantic.not_a_record"
	CodeNotExported           diagnostic.Code = "masterbelt.semantic.not_exported"
	CodeRefinementNotBool     diagnostic.Code = "masterbelt.semantic.refinement_not_bool"
	CodeRefinementNotConstant diagnostic.Code = "masterbelt.semantic.refinement_not_constant"
	CodeRefinementViolation   diagnostic.Code = "masterbelt.semantic.refinement_violation"
	CodeTypeMismatch          diagnostic.Code = "masterbelt.semantic.type_mismatch"
	CodeUndefinedName         diagnostic.Code = "masterbelt.semantic.undefined_name"
	CodeUninferableCollection diagnostic.Code = "masterbelt.semantic.uninferable_collection"
	CodeUninferableParameter  diagnostic.Code = "masterbelt.semantic.uninferable_parameter"
	CodeUninferableRecord     diagnostic.Code = "masterbelt.semantic.uninferable_record"
	CodeUninferableResult     diagnostic.Code = "masterbelt.semantic.uninferable_result"
	CodeUnknownField          diagnostic.Code = "masterbelt.semantic.unknown_field"
	CodeUnknownMember         diagnostic.Code = "masterbelt.semantic.unknown_member"
	CodeUnknownType           diagnostic.Code = "masterbelt.semantic.unknown_type"
	CodeUseNotFound           diagnostic.Code = "masterbelt.semantic.use_not_found"
)

func newAmbiguousImportDiagnostic(offset int, width int, name string) diagnostic.Diagnostic {
	fields := map[string]fmt.Stringer{
		"name": diagnostic.Str(name),
	}
	return diagnostic.Diagnostic{
		Severity: diagnostic.Error,
		Code:     CodeAmbiguousImport,
		Message:  diagnostic.Render(diagnostic.DefaultLocale, CodeAmbiguousImport, fields),
		Fields:   fields,
		Offset:   offset,
		Width:    width,
	}
}

func newAmbiguousOverloadDiagnostic(offset int, width int, method string, types string) diagnostic.Diagnostic {
	fields := map[string]fmt.Stringer{
		"method": diagnostic.Str(method),
		"types":  diagnostic.Str(types),
	}
	return diagnostic.Diagnostic{
		Severity: diagnostic.Error,
		Code:     CodeAmbiguousOverload,
		Message:  diagnostic.Render(diagnostic.DefaultLocale, CodeAmbiguousOverload, fields),
		Fields:   fields,
		Offset:   offset,
		Width:    width,
	}
}

func newAssertionFailedDiagnostic(offset int, width int, cond string, doc string, diagram string) diagnostic.Diagnostic {
	fields := map[string]fmt.Stringer{
		"cond":    diagnostic.Str(cond),
		"doc":     diagnostic.Str(doc),
		"diagram": diagnostic.Str(diagram),
	}
	return diagnostic.Diagnostic{
		Severity: diagnostic.Error,
		Code:     CodeAssertionFailed,
		Message:  diagnostic.Render(diagnostic.DefaultLocale, CodeAssertionFailed, fields),
		Fields:   fields,
		Offset:   offset,
		Width:    width,
	}
}

func newAssertionNotBoolDiagnostic(offset int, width int, typ string) diagnostic.Diagnostic {
	fields := map[string]fmt.Stringer{
		"typ": diagnostic.Str(typ),
	}
	return diagnostic.Diagnostic{
		Severity: diagnostic.Error,
		Code:     CodeAssertionNotBool,
		Message:  diagnostic.Render(diagnostic.DefaultLocale, CodeAssertionNotBool, fields),
		Fields:   fields,
		Offset:   offset,
		Width:    width,
	}
}

func newAssertionNotConstantDiagnostic(offset int, width int) diagnostic.Diagnostic {
	return diagnostic.Diagnostic{
		Severity: diagnostic.Error,
		Code:     CodeAssertionNotConstant,
		Message:  diagnostic.Render(diagnostic.DefaultLocale, CodeAssertionNotConstant, nil),
		Fields:   nil,
		Offset:   offset,
		Width:    width,
	}
}

func newConstantOverflowDiagnostic(offset int, width int, value string, typ string) diagnostic.Diagnostic {
	fields := map[string]fmt.Stringer{
		"value": diagnostic.Str(value),
		"typ":   diagnostic.Str(typ),
	}
	return diagnostic.Diagnostic{
		Severity: diagnostic.Error,
		Code:     CodeConstantOverflow,
		Message:  diagnostic.Render(diagnostic.DefaultLocale, CodeConstantOverflow, fields),
		Fields:   fields,
		Offset:   offset,
		Width:    width,
	}
}

func newCyclicModuleDiagnostic(offset int, width int, path string) diagnostic.Diagnostic {
	fields := map[string]fmt.Stringer{
		"path": diagnostic.Str(path),
	}
	return diagnostic.Diagnostic{
		Severity: diagnostic.Error,
		Code:     CodeCyclicModule,
		Message:  diagnostic.Render(diagnostic.DefaultLocale, CodeCyclicModule, fields),
		Fields:   fields,
		Offset:   offset,
		Width:    width,
	}
}

func newCyclicReferenceDiagnostic(offset int, width int, name string) diagnostic.Diagnostic {
	fields := map[string]fmt.Stringer{
		"name": diagnostic.Str(name),
	}
	return diagnostic.Diagnostic{
		Severity: diagnostic.Error,
		Code:     CodeCyclicReference,
		Message:  diagnostic.Render(diagnostic.DefaultLocale, CodeCyclicReference, fields),
		Fields:   fields,
		Offset:   offset,
		Width:    width,
	}
}

func newDivisionByZeroDiagnostic(offset int, width int) diagnostic.Diagnostic {
	return diagnostic.Diagnostic{
		Severity: diagnostic.Error,
		Code:     CodeDivisionByZero,
		Message:  diagnostic.Render(diagnostic.DefaultLocale, CodeDivisionByZero, nil),
		Fields:   nil,
		Offset:   offset,
		Width:    width,
	}
}

func newDuplicateDeclarationDiagnostic(offset int, width int, name string) diagnostic.Diagnostic {
	fields := map[string]fmt.Stringer{
		"name": diagnostic.Str(name),
	}
	return diagnostic.Diagnostic{
		Severity: diagnostic.Error,
		Code:     CodeDuplicateDeclaration,
		Message:  diagnostic.Render(diagnostic.DefaultLocale, CodeDuplicateDeclaration, fields),
		Fields:   fields,
		Offset:   offset,
		Width:    width,
	}
}

func newDuplicateOverloadDiagnostic(offset int, width int, method string, types string) diagnostic.Diagnostic {
	fields := map[string]fmt.Stringer{
		"method": diagnostic.Str(method),
		"types":  diagnostic.Str(types),
	}
	return diagnostic.Diagnostic{
		Severity: diagnostic.Error,
		Code:     CodeDuplicateOverload,
		Message:  diagnostic.Render(diagnostic.DefaultLocale, CodeDuplicateOverload, fields),
		Fields:   fields,
		Offset:   offset,
		Width:    width,
	}
}

func newInvalidOperationDiagnostic(offset int, width int, method string, types string) diagnostic.Diagnostic {
	fields := map[string]fmt.Stringer{
		"method": diagnostic.Str(method),
		"types":  diagnostic.Str(types),
	}
	return diagnostic.Diagnostic{
		Severity: diagnostic.Error,
		Code:     CodeInvalidOperation,
		Message:  diagnostic.Render(diagnostic.DefaultLocale, CodeInvalidOperation, fields),
		Fields:   fields,
		Offset:   offset,
		Width:    width,
	}
}

func newLambdaArityMismatchDiagnostic(offset int, width int, actual int, expected int) diagnostic.Diagnostic {
	fields := map[string]fmt.Stringer{
		"actual":   diagnostic.Int(actual),
		"expected": diagnostic.Int(expected),
	}
	return diagnostic.Diagnostic{
		Severity: diagnostic.Error,
		Code:     CodeLambdaArityMismatch,
		Message:  diagnostic.Render(diagnostic.DefaultLocale, CodeLambdaArityMismatch, fields),
		Fields:   fields,
		Offset:   offset,
		Width:    width,
	}
}

func newMissingFieldDiagnostic(offset int, width int, field string, typ string) diagnostic.Diagnostic {
	fields := map[string]fmt.Stringer{
		"field": diagnostic.Str(field),
		"typ":   diagnostic.Str(typ),
	}
	return diagnostic.Diagnostic{
		Severity: diagnostic.Error,
		Code:     CodeMissingField,
		Message:  diagnostic.Render(diagnostic.DefaultLocale, CodeMissingField, fields),
		Fields:   fields,
		Offset:   offset,
		Width:    width,
	}
}

func newNoMatchingOverloadDiagnostic(offset int, width int, method string, types string) diagnostic.Diagnostic {
	fields := map[string]fmt.Stringer{
		"method": diagnostic.Str(method),
		"types":  diagnostic.Str(types),
	}
	return diagnostic.Diagnostic{
		Severity: diagnostic.Error,
		Code:     CodeNoMatchingOverload,
		Message:  diagnostic.Render(diagnostic.DefaultLocale, CodeNoMatchingOverload, fields),
		Fields:   fields,
		Offset:   offset,
		Width:    width,
	}
}

func newNotARecordDiagnostic(offset int, width int, typ string) diagnostic.Diagnostic {
	fields := map[string]fmt.Stringer{
		"typ": diagnostic.Str(typ),
	}
	return diagnostic.Diagnostic{
		Severity: diagnostic.Error,
		Code:     CodeNotARecord,
		Message:  diagnostic.Render(diagnostic.DefaultLocale, CodeNotARecord, fields),
		Fields:   fields,
		Offset:   offset,
		Width:    width,
	}
}

func newNotExportedDiagnostic(offset int, width int, name string, path string) diagnostic.Diagnostic {
	fields := map[string]fmt.Stringer{
		"name": diagnostic.Str(name),
		"path": diagnostic.Str(path),
	}
	return diagnostic.Diagnostic{
		Severity: diagnostic.Error,
		Code:     CodeNotExported,
		Message:  diagnostic.Render(diagnostic.DefaultLocale, CodeNotExported, fields),
		Fields:   fields,
		Offset:   offset,
		Width:    width,
	}
}

func newRefinementNotBoolDiagnostic(offset int, width int, typ string) diagnostic.Diagnostic {
	fields := map[string]fmt.Stringer{
		"typ": diagnostic.Str(typ),
	}
	return diagnostic.Diagnostic{
		Severity: diagnostic.Error,
		Code:     CodeRefinementNotBool,
		Message:  diagnostic.Render(diagnostic.DefaultLocale, CodeRefinementNotBool, fields),
		Fields:   fields,
		Offset:   offset,
		Width:    width,
	}
}

func newRefinementNotConstantDiagnostic(offset int, width int) diagnostic.Diagnostic {
	return diagnostic.Diagnostic{
		Severity: diagnostic.Error,
		Code:     CodeRefinementNotConstant,
		Message:  diagnostic.Render(diagnostic.DefaultLocale, CodeRefinementNotConstant, nil),
		Fields:   nil,
		Offset:   offset,
		Width:    width,
	}
}

func newRefinementViolationDiagnostic(offset int, width int, value string, typ string, predicate string, diagram string) diagnostic.Diagnostic {
	fields := map[string]fmt.Stringer{
		"value":     diagnostic.Str(value),
		"typ":       diagnostic.Str(typ),
		"predicate": diagnostic.Str(predicate),
		"diagram":   diagnostic.Str(diagram),
	}
	return diagnostic.Diagnostic{
		Severity: diagnostic.Error,
		Code:     CodeRefinementViolation,
		Message:  diagnostic.Render(diagnostic.DefaultLocale, CodeRefinementViolation, fields),
		Fields:   fields,
		Offset:   offset,
		Width:    width,
	}
}

func newTypeMismatchDiagnostic(offset int, width int, actual string, expected string) diagnostic.Diagnostic {
	fields := map[string]fmt.Stringer{
		"actual":   diagnostic.Str(actual),
		"expected": diagnostic.Str(expected),
	}
	return diagnostic.Diagnostic{
		Severity: diagnostic.Error,
		Code:     CodeTypeMismatch,
		Message:  diagnostic.Render(diagnostic.DefaultLocale, CodeTypeMismatch, fields),
		Fields:   fields,
		Offset:   offset,
		Width:    width,
	}
}

func newUndefinedNameDiagnostic(offset int, width int, name string) diagnostic.Diagnostic {
	fields := map[string]fmt.Stringer{
		"name": diagnostic.Str(name),
	}
	return diagnostic.Diagnostic{
		Severity: diagnostic.Error,
		Code:     CodeUndefinedName,
		Message:  diagnostic.Render(diagnostic.DefaultLocale, CodeUndefinedName, fields),
		Fields:   fields,
		Offset:   offset,
		Width:    width,
	}
}

func newUninferableCollectionDiagnostic(offset int, width int) diagnostic.Diagnostic {
	return diagnostic.Diagnostic{
		Severity: diagnostic.Error,
		Code:     CodeUninferableCollection,
		Message:  diagnostic.Render(diagnostic.DefaultLocale, CodeUninferableCollection, nil),
		Fields:   nil,
		Offset:   offset,
		Width:    width,
	}
}

func newUninferableParameterDiagnostic(offset int, width int, name string) diagnostic.Diagnostic {
	fields := map[string]fmt.Stringer{
		"name": diagnostic.Str(name),
	}
	return diagnostic.Diagnostic{
		Severity: diagnostic.Error,
		Code:     CodeUninferableParameter,
		Message:  diagnostic.Render(diagnostic.DefaultLocale, CodeUninferableParameter, fields),
		Fields:   fields,
		Offset:   offset,
		Width:    width,
	}
}

func newUninferableRecordDiagnostic(offset int, width int) diagnostic.Diagnostic {
	return diagnostic.Diagnostic{
		Severity: diagnostic.Error,
		Code:     CodeUninferableRecord,
		Message:  diagnostic.Render(diagnostic.DefaultLocale, CodeUninferableRecord, nil),
		Fields:   nil,
		Offset:   offset,
		Width:    width,
	}
}

func newUninferableResultDiagnostic(offset int, width int) diagnostic.Diagnostic {
	return diagnostic.Diagnostic{
		Severity: diagnostic.Error,
		Code:     CodeUninferableResult,
		Message:  diagnostic.Render(diagnostic.DefaultLocale, CodeUninferableResult, nil),
		Fields:   nil,
		Offset:   offset,
		Width:    width,
	}
}

func newUnknownFieldDiagnostic(offset int, width int, field string, typ string) diagnostic.Diagnostic {
	fields := map[string]fmt.Stringer{
		"field": diagnostic.Str(field),
		"typ":   diagnostic.Str(typ),
	}
	return diagnostic.Diagnostic{
		Severity: diagnostic.Error,
		Code:     CodeUnknownField,
		Message:  diagnostic.Render(diagnostic.DefaultLocale, CodeUnknownField, fields),
		Fields:   fields,
		Offset:   offset,
		Width:    width,
	}
}

func newUnknownMemberDiagnostic(offset int, width int, name string, namespace string) diagnostic.Diagnostic {
	fields := map[string]fmt.Stringer{
		"name":      diagnostic.Str(name),
		"namespace": diagnostic.Str(namespace),
	}
	return diagnostic.Diagnostic{
		Severity: diagnostic.Error,
		Code:     CodeUnknownMember,
		Message:  diagnostic.Render(diagnostic.DefaultLocale, CodeUnknownMember, fields),
		Fields:   fields,
		Offset:   offset,
		Width:    width,
	}
}

func newUnknownTypeDiagnostic(offset int, width int, name string) diagnostic.Diagnostic {
	fields := map[string]fmt.Stringer{
		"name": diagnostic.Str(name),
	}
	return diagnostic.Diagnostic{
		Severity: diagnostic.Error,
		Code:     CodeUnknownType,
		Message:  diagnostic.Render(diagnostic.DefaultLocale, CodeUnknownType, fields),
		Fields:   fields,
		Offset:   offset,
		Width:    width,
	}
}

func newUseNotFoundDiagnostic(offset int, width int, path string) diagnostic.Diagnostic {
	fields := map[string]fmt.Stringer{
		"path": diagnostic.Str(path),
	}
	return diagnostic.Diagnostic{
		Severity: diagnostic.Error,
		Code:     CodeUseNotFound,
		Message:  diagnostic.Render(diagnostic.DefaultLocale, CodeUseNotFound, fields),
		Fields:   fields,
		Offset:   offset,
		Width:    width,
	}
}
