// Code generated by "go generate"; DO NOT EDIT.

package lexer

import (
	"fmt"

	"github.com/masterbelt/masterbelt/pkg/masterbelt/diagnostic"
	"github.com/masterbelt/masterbelt/pkg/masterbelt/source"
)

const (
	CodeUnexpectedCharacter      diagnostic.Code = "masterbelt.lexer.unexpected_character"
	CodeUnterminatedBlockComment diagnostic.Code = "masterbelt.lexer.unterminated_block_comment"
)

func newUnexpectedCharacterDiagnostic(span source.Span, char rune) diagnostic.Diagnostic {
	fields := map[string]fmt.Stringer{
		"char": diagnostic.Rune(char),
	}
	return diagnostic.Diagnostic{
		Severity: diagnostic.Error,
		Code:     CodeUnexpectedCharacter,
		Message:  diagnostic.Render(diagnostic.DefaultLocale, CodeUnexpectedCharacter, fields),
		Fields:   fields,
		Span:     span,
	}
}

func newUnterminatedBlockCommentDiagnostic(span source.Span) diagnostic.Diagnostic {
	return diagnostic.Diagnostic{
		Severity: diagnostic.Error,
		Code:     CodeUnterminatedBlockComment,
		Message:  diagnostic.Render(diagnostic.DefaultLocale, CodeUnterminatedBlockComment, nil),
		Fields:   nil,
		Span:     span,
	}
}
