// Code generated by "go generate"; DO NOT EDIT.

package master

import (
	"fmt"

	"github.com/masterbelt/masterbelt/pkg/diagnostic"
)

const (
	CodeCellRefinement       diagnostic.Code = "master.cell_refinement"
	CodeCellTypeMismatch     diagnostic.Code = "master.cell_type_mismatch"
	CodeDuplicateOption      diagnostic.Code = "master.duplicate_option"
	CodeDuplicatePrimaryKey  diagnostic.Code = "master.duplicate_primary_key"
	CodeDuplicateRowField    diagnostic.Code = "master.duplicate_row_field"
	CodeLocatorEscapesRoot   diagnostic.Code = "master.locator_escapes_root"
	CodeMissingColumn        diagnostic.Code = "master.missing_column"
	CodeOptionTypeMismatch   diagnostic.Code = "master.option_type_mismatch"
	CodeRowValidationFailed  diagnostic.Code = "master.row_validation_failed"
	CodeSourceUnreadable     diagnostic.Code = "master.source_unreadable"
	CodeUnknownFormat        diagnostic.Code = "master.unknown_format"
	CodeUnknownOption        diagnostic.Code = "master.unknown_option"
	CodeUnsupportedFieldType diagnostic.Code = "master.unsupported_field_type"
	CodeUnsupportedRowType   diagnostic.Code = "master.unsupported_row_type"
)

func newCellRefinementDiagnostic(offset int, width int, path string, row int, col int, field string, value string, typ string) diagnostic.Diagnostic {
	fields := map[string]fmt.Stringer{
		"path":  diagnostic.Str(path),
		"row":   diagnostic.Int(row),
		"col":   diagnostic.Int(col),
		"field": diagnostic.Str(field),
		"value": diagnostic.Str(value),
		"typ":   diagnostic.Str(typ),
	}
	return diagnostic.Diagnostic{
		Severity: diagnostic.Error,
		Code:     CodeCellRefinement,
		Message:  diagnostic.Render(diagnostic.DefaultLocale, CodeCellRefinement, fields),
		Fields:   fields,
		Offset:   offset,
		Width:    width,
	}
}

func newCellTypeMismatchDiagnostic(offset int, width int, path string, row int, col int, field string, value string, typ string) diagnostic.Diagnostic {
	fields := map[string]fmt.Stringer{
		"path":  diagnostic.Str(path),
		"row":   diagnostic.Int(row),
		"col":   diagnostic.Int(col),
		"field": diagnostic.Str(field),
		"value": diagnostic.Str(value),
		"typ":   diagnostic.Str(typ),
	}
	return diagnostic.Diagnostic{
		Severity: diagnostic.Error,
		Code:     CodeCellTypeMismatch,
		Message:  diagnostic.Render(diagnostic.DefaultLocale, CodeCellTypeMismatch, fields),
		Fields:   fields,
		Offset:   offset,
		Width:    width,
	}
}

func newDuplicateOptionDiagnostic(offset int, width int, format string, key string) diagnostic.Diagnostic {
	fields := map[string]fmt.Stringer{
		"format": diagnostic.Str(format),
		"key":    diagnostic.Str(key),
	}
	return diagnostic.Diagnostic{
		Severity: diagnostic.Error,
		Code:     CodeDuplicateOption,
		Message:  diagnostic.Render(diagnostic.DefaultLocale, CodeDuplicateOption, fields),
		Fields:   fields,
		Offset:   offset,
		Width:    width,
	}
}

func newDuplicatePrimaryKeyDiagnostic(offset int, width int, path string, row int, col int, key string, first int) diagnostic.Diagnostic {
	fields := map[string]fmt.Stringer{
		"path":  diagnostic.Str(path),
		"row":   diagnostic.Int(row),
		"col":   diagnostic.Int(col),
		"key":   diagnostic.Str(key),
		"first": diagnostic.Int(first),
	}
	return diagnostic.Diagnostic{
		Severity: diagnostic.Error,
		Code:     CodeDuplicatePrimaryKey,
		Message:  diagnostic.Render(diagnostic.DefaultLocale, CodeDuplicatePrimaryKey, fields),
		Fields:   fields,
		Offset:   offset,
		Width:    width,
	}
}

func newDuplicateRowFieldDiagnostic(offset int, width int, field string, master string) diagnostic.Diagnostic {
	fields := map[string]fmt.Stringer{
		"field":  diagnostic.Str(field),
		"master": diagnostic.Str(master),
	}
	return diagnostic.Diagnostic{
		Severity: diagnostic.Error,
		Code:     CodeDuplicateRowField,
		Message:  diagnostic.Render(diagnostic.DefaultLocale, CodeDuplicateRowField, fields),
		Fields:   fields,
		Offset:   offset,
		Width:    width,
	}
}

func newLocatorEscapesRootDiagnostic(offset int, width int, path string) diagnostic.Diagnostic {
	fields := map[string]fmt.Stringer{
		"path": diagnostic.Str(path),
	}
	return diagnostic.Diagnostic{
		Severity: diagnostic.Error,
		Code:     CodeLocatorEscapesRoot,
		Message:  diagnostic.Render(diagnostic.DefaultLocale, CodeLocatorEscapesRoot, fields),
		Fields:   fields,
		Offset:   offset,
		Width:    width,
	}
}

func newMissingColumnDiagnostic(offset int, width int, field string, path string) diagnostic.Diagnostic {
	fields := map[string]fmt.Stringer{
		"field": diagnostic.Str(field),
		"path":  diagnostic.Str(path),
	}
	return diagnostic.Diagnostic{
		Severity: diagnostic.Error,
		Code:     CodeMissingColumn,
		Message:  diagnostic.Render(diagnostic.DefaultLocale, CodeMissingColumn, fields),
		Fields:   fields,
		Offset:   offset,
		Width:    width,
	}
}

func newOptionTypeMismatchDiagnostic(offset int, width int, key string, typ string) diagnostic.Diagnostic {
	fields := map[string]fmt.Stringer{
		"key": diagnostic.Str(key),
		"typ": diagnostic.Str(typ),
	}
	return diagnostic.Diagnostic{
		Severity: diagnostic.Error,
		Code:     CodeOptionTypeMismatch,
		Message:  diagnostic.Render(diagnostic.DefaultLocale, CodeOptionTypeMismatch, fields),
		Fields:   fields,
		Offset:   offset,
		Width:    width,
	}
}

func newRowValidationFailedDiagnostic(offset int, width int, path string, row int) diagnostic.Diagnostic {
	fields := map[string]fmt.Stringer{
		"path": diagnostic.Str(path),
		"row":  diagnostic.Int(row),
	}
	return diagnostic.Diagnostic{
		Severity: diagnostic.Error,
		Code:     CodeRowValidationFailed,
		Message:  diagnostic.Render(diagnostic.DefaultLocale, CodeRowValidationFailed, fields),
		Fields:   fields,
		Offset:   offset,
		Width:    width,
	}
}

func newSourceUnreadableDiagnostic(offset int, width int, path string, detail string) diagnostic.Diagnostic {
	fields := map[string]fmt.Stringer{
		"path":   diagnostic.Str(path),
		"detail": diagnostic.Str(detail),
	}
	return diagnostic.Diagnostic{
		Severity: diagnostic.Error,
		Code:     CodeSourceUnreadable,
		Message:  diagnostic.Render(diagnostic.DefaultLocale, CodeSourceUnreadable, fields),
		Fields:   fields,
		Offset:   offset,
		Width:    width,
	}
}

func newUnknownFormatDiagnostic(offset int, width int, format string) diagnostic.Diagnostic {
	fields := map[string]fmt.Stringer{
		"format": diagnostic.Str(format),
	}
	return diagnostic.Diagnostic{
		Severity: diagnostic.Error,
		Code:     CodeUnknownFormat,
		Message:  diagnostic.Render(diagnostic.DefaultLocale, CodeUnknownFormat, fields),
		Fields:   fields,
		Offset:   offset,
		Width:    width,
	}
}

func newUnknownOptionDiagnostic(offset int, width int, format string, key string) diagnostic.Diagnostic {
	fields := map[string]fmt.Stringer{
		"format": diagnostic.Str(format),
		"key":    diagnostic.Str(key),
	}
	return diagnostic.Diagnostic{
		Severity: diagnostic.Error,
		Code:     CodeUnknownOption,
		Message:  diagnostic.Render(diagnostic.DefaultLocale, CodeUnknownOption, fields),
		Fields:   fields,
		Offset:   offset,
		Width:    width,
	}
}

func newUnsupportedFieldTypeDiagnostic(offset int, width int, field string, typ string) diagnostic.Diagnostic {
	fields := map[string]fmt.Stringer{
		"field": diagnostic.Str(field),
		"typ":   diagnostic.Str(typ),
	}
	return diagnostic.Diagnostic{
		Severity: diagnostic.Error,
		Code:     CodeUnsupportedFieldType,
		Message:  diagnostic.Render(diagnostic.DefaultLocale, CodeUnsupportedFieldType, fields),
		Fields:   fields,
		Offset:   offset,
		Width:    width,
	}
}

func newUnsupportedRowTypeDiagnostic(offset int, width int, master string) diagnostic.Diagnostic {
	fields := map[string]fmt.Stringer{
		"master": diagnostic.Str(master),
	}
	return diagnostic.Diagnostic{
		Severity: diagnostic.Error,
		Code:     CodeUnsupportedRowType,
		Message:  diagnostic.Render(diagnostic.DefaultLocale, CodeUnsupportedRowType, fields),
		Fields:   fields,
		Offset:   offset,
		Width:    width,
	}
}
