package main

import (
	"fmt"
	"strings"

	"github.com/masterbelt/masterbelt/pkg/source/token"
)

// queriesDir holds the generated tree-sitter highlight queries. The default
// queries/highlights.scm follows nvim-treesitter's capture names (the de facto
// standard, and what GitHub's tree-sitter path reads); editors whose capture
// vocabulary differs get a variant in queries/<editor>/highlights.scm. There is
// one source — the category table and the node->category rules below — and the
// generator absorbs the per-editor naming differences (C-2 plan §4).
const queriesDir = treeSitterDir + "/queries"

// Two highlight sub-categories the cold-start layer distinguishes that are not
// among semantic.go's 13 token types: a doc comment and a string escape. They
// ride alongside the canonical categories in the capture maps.
const (
	catCommentDoc   = "comment.doc"
	catStringEscape = "string.escape"
)

// tsTarget is a highlight target: an editor family and the capture name it uses
// for each canonical category (semantic.go's vocabulary, plus the two
// sub-categories above). Only the names differ between editors; the query
// structure — which node carries which category — is shared.
type tsTarget struct {
	// dir is the subdirectory under queries/ ("" is the default, nvim-flavored,
	// which tree-sitter.json points at).
	dir     string
	capture map[string]string // canonical category -> capture name, no leading '@'
}

// cap is the target's capture token (with the leading '@') for a category. A
// target's own map lists only the captures where it diverges from the default
// (nvim) vocabulary, so cap falls back to defaultCaptures, then to the category
// name itself.
func (t tsTarget) cap(category string) string {
	if c, ok := t.capture[category]; ok {
		return "@" + c
	}
	if c, ok := defaultCaptures[category]; ok {
		return "@" + c
	}
	return "@" + category
}

// defaultCaptures is the nvim-treesitter vocabulary — the base every target
// inherits (and what GitHub's tree-sitter path reads). A target overrides only
// where its convention differs (see tsTargets), so the shared names live here
// once.
var defaultCaptures = map[string]string{
	catKeyword: "keyword", catComment: "comment", catCommentDoc: "comment.documentation",
	catType: "type", catVariable: "variable", catNumber: "number",
	catString: "string", catStringEscape: "string.escape", catOperator: "operator",
	catNamespace: "module", catProperty: "property", catMethod: "function.method",
	catParameter: "variable.parameter", catFunction: "function", catEnumMember: "constant",
}

// tsTargets are the highlight targets generated. The default (nvim-treesitter)
// carries no overrides; helix and zed list only the captures whose names differ
// from the default — the differences the generator exists to absorb (C-2 §4).
var tsTargets = []tsTarget{
	{dir: ""}, // nvim-treesitter (and GitHub): the default vocabulary
	{dir: "helix", capture: map[string]string{
		catCommentDoc:   "comment.block.documentation",
		catNumber:       "constant.numeric.integer",
		catStringEscape: "constant.character.escape",
		catNamespace:    "namespace",
		catProperty:     "variable.other.member",
	}},
	{dir: "zed", capture: map[string]string{
		catCommentDoc: "comment.doc",
		catNamespace:  "namespace",
	}},
}

// semanticOperatorSpellings is the operator set the language server colours as
// `operator` (semantic.go's classifyToken): the type/assignment colon and
// equals, the arrow, the ternary question mark, and the two range operators.
// The arithmetic and comparison operators are deliberately left uncoloured at
// cold start, exactly as the server and the TextMate grammar leave them.
func semanticOperatorSpellings() []string {
	return []string{
		token.Colon.Symbol(), token.Assign.Symbol(), token.Arrow.Symbol(),
		token.Question.Symbol(), token.DotDot.Symbol(), token.DotDotDot.Symbol(),
	}
}

// contextModifiers are contextual accessor/static modifiers: `get`, `set`, and
// `static`. They are intentionally not reserved words in token.Keywords because
// they should remain legal identifiers outside modifier positions; the lexer
// therefore emits them as identifiers. During highlighting, when they appear in
// modifier/accessor context, we promote them to keyword colouring (keyword.control),
// matching semantic.go's Modifier handling and the TextMate #modifiers rule.
var contextModifiers = []string{"get", "set", "static"}

// buildHighlights renders one target's highlights.scm. The node->category
// structure is identical across targets; t.cap projects each category to the
// target's capture name. Later patterns win in tree-sitter highlighting, so the
// contextual overrides (a call's callee is a function, not a plain variable)
// follow the general identifier rules.
func buildHighlights(t tsTarget) string {
	var b strings.Builder
	fmt.Fprintf(&b, `; Code generated by editorgen; DO NOT EDIT.
;
; tree-sitter highlight queries for masterbelt, projected from the category
; table (the language server's semantic token types) to %s's capture names.
; The query structure is shared across editors; only the capture names differ.

`, targetLabel(t))

	// Comments. A doc comment gets its own capture; the line and block forms
	// share the plain comment capture.
	fmt.Fprintf(&b, "(doc_comment) %s\n", t.cap(catCommentDoc))
	fmt.Fprintf(&b, "[(line_comment) (block_comment)] %s\n\n", t.cap(catComment))

	// Literals. datetime and duration colour as numbers, as in the cold-start
	// TextMate grammar; the escape sits inside the string.
	fmt.Fprintf(&b, "[(integer) (datetime) (duration)] %s\n", t.cap(catNumber))
	fmt.Fprintf(&b, "(escape_sequence) %s\n", t.cap(catStringEscape))
	fmt.Fprintf(&b, "(string) %s\n\n", t.cap(catString))

	// Keywords — the reserved words plus the accessor/static context keywords,
	// uniformly (true/false/null and the effect words are reserved, so they are
	// in the list), matching semantic.go's uniform keyword classification.
	b.WriteString("[\n")
	for _, kw := range token.Keywords() {
		fmt.Fprintf(&b, "  %q\n", kw)
	}
	for _, m := range contextModifiers {
		fmt.Fprintf(&b, "  %q\n", m)
	}
	fmt.Fprintf(&b, "] %s\n\n", t.cap(catKeyword))

	// Operators — the server's operator set.
	b.WriteString("[\n")
	for _, sym := range semanticOperatorSpellings() {
		fmt.Fprintf(&b, "  %q\n", sym)
	}
	fmt.Fprintf(&b, "] %s\n\n", t.cap(catOperator))

	// Declared names. The kind of declaration fixes the colour, matching
	// semantic.go's identClasses.
	fmt.Fprintf(&b, "(const_decl name: (identifier) %s)\n", t.cap(catVariable))
	fmt.Fprintf(&b, "(let_stmt name: (identifier) %s)\n", t.cap(catVariable))
	fmt.Fprintf(&b, "(type_decl name: (identifier) %s)\n", t.cap(catType))
	fmt.Fprintf(&b, "(enum_decl name: (identifier) %s)\n", t.cap(catType))
	fmt.Fprintf(&b, "(interface_decl name: (identifier) %s)\n", t.cap(catType))
	fmt.Fprintf(&b, "(generic_param name: (identifier) %s)\n", t.cap(catType))
	fmt.Fprintf(&b, "(func_decl name: (identifier) %s)\n", t.cap(catFunction))
	fmt.Fprintf(&b, "(method_decl name: (identifier) %s)\n", t.cap(catMethod))
	fmt.Fprintf(&b, "(interface_member name: (identifier) %s)\n", t.cap(catMethod))
	fmt.Fprintf(&b, "(param name: (identifier) %s)\n", t.cap(catParameter))
	fmt.Fprintf(&b, "(field name: (identifier) %s)\n", t.cap(catProperty))
	fmt.Fprintf(&b, "(record_field name: (identifier) %s)\n", t.cap(catProperty))
	fmt.Fprintf(&b, "(enum_member name: (identifier) %s)\n", t.cap(catEnumMember))
	fmt.Fprintf(&b, "(use_decl (identifier) %s)\n", t.cap(catNamespace))
	fmt.Fprintf(&b, "(modifier) %s\n\n", t.cap(catKeyword))

	// References. A name in a type position is a type; the type prefix of a
	// record literal is too. A bare value reference is a variable, and a member
	// access reads as a property.
	fmt.Fprintf(&b, "(type_name (identifier) %s)\n", t.cap(catType))
	fmt.Fprintf(&b, "(record_literal type: (identifier) %s)\n", t.cap(catType))
	fmt.Fprintf(&b, "(value_ref (identifier) %s)\n", t.cap(catVariable))
	fmt.Fprintf(&b, "(member_expr member: (identifier) %s)\n\n", t.cap(catProperty))

	// Contextual overrides (later, so they win): a call's callee names the
	// function or method being called, not a plain value or property.
	fmt.Fprintf(&b, "(call_expr callee: (value_ref (identifier) %s))\n", t.cap(catFunction))
	fmt.Fprintf(&b, "(call_expr callee: (member_expr member: (identifier) %s))\n", t.cap(catMethod))

	return b.String()
}

// targetLabel names a target for the generated file's header comment.
func targetLabel(t tsTarget) string {
	if t.dir == "" {
		return "nvim-treesitter (the default)"
	}
	return t.dir
}

// highlightPath is the output path for a target's highlights.scm: the default
// target writes queries/highlights.scm, the rest queries/<dir>/highlights.scm.
func highlightPath(t tsTarget) string {
	if t.dir == "" {
		return queriesDir + "/highlights.scm"
	}
	return queriesDir + "/" + t.dir + "/highlights.scm"
}

// writeQueries emits every target's highlights.scm.
func writeQueries() error {
	for _, t := range tsTargets {
		if err := writeFile(highlightPath(t), buildHighlights(t)); err != nil {
			return err
		}
	}
	return nil
}
