package main

import (
	"fmt"
	"strings"

	"github.com/masterbelt/masterbelt/pkg/source/token"
)

// treeSitterDir is the tree-sitter grammar package, relative to this package's
// directory (where `go generate` runs). editorgen writes the generated lexical
// layer there; the hand-written grammar.js and the tree-sitter-generated src/
// live alongside it (C-2 plan §6).
const treeSitterDir = "../../grammars/tree-sitter-masterbelt"

// lexicalPath is the generated lexical module grammar.js requires.
const lexicalPath = treeSitterDir + "/lexical.js"

// buildLexicalJS renders the tree-sitter grammar's lexical layer as a CommonJS
// module: the keyword table, operator spellings, comment markers, and literal
// regexes the lexer commits on — the same lexer truth (package token + the
// shared regexes) the TextMate grammar is generated from. The hand-written
// grammar.js requires it and builds the structural rules on top, so the second
// parser's lexer cannot drift from the real one (C-2 plan §2-3). It is the
// tree-sitter sibling of buildGrammar's TextMate projection.
func buildLexicalJS() string {
	var b strings.Builder
	b.WriteString(`// Code generated by editorgen from pkg/source/token; DO NOT EDIT.
//
// The lexical layer of the masterbelt tree-sitter grammar: the keyword table,
// operator spellings, comment markers, and literal regexes the lexer commits
// on — the same lexer truth the TextMate grammar is generated from. The
// hand-written grammar.js requires this module and builds the structural rules
// on top, so the second parser's lexer cannot drift from the real one.

module.exports = {
`)

	// The shared language identity (C-2 §6): the parser name matches the
	// TextMate scope's source.<name> and the file extension .belt.
	fmt.Fprintf(&b, "  // The language identity shared across every target (C-2 §6).\n")
	fmt.Fprintf(&b, "  name: %q,\n\n", langName)

	b.WriteString("  // The identifier / word rule. Declared as the grammar's `word` token, so\n")
	b.WriteString("  // the keywords below lex as keywords rather than as identifiers.\n")
	fmt.Fprintf(&b, "  identifier: /%s/,\n\n", reIdentifier)

	b.WriteString("  // Reserved words, by spelling; referenced by name from grammar.js (kw.const).\n")
	b.WriteString("  kw: {\n")
	for _, kw := range token.Keywords() {
		fmt.Fprintf(&b, "    %q: %q,\n", kw, kw)
	}
	b.WriteString("  },\n\n")

	b.WriteString("  // Fixed operator and punctuation spellings, by token kind name (op.Arrow).\n")
	b.WriteString("  op: {\n")
	for _, op := range token.Operators() {
		fmt.Fprintf(&b, "    %q: %q,\n", op.Name, op.Symbol)
	}
	b.WriteString("  },\n\n")

	b.WriteString("  // Literal token regexes. grammar.js tries datetime and duration before a\n")
	b.WriteString("  // bare integer; tree-sitter's longest-match then makes \"3w4d\" a duration\n")
	b.WriteString("  // and \"100\" an integer.\n")
	fmt.Fprintf(&b, "  integer: /%s/,\n", reInteger)
	fmt.Fprintf(&b, "  datetime: /%s/,\n", reDatetime)
	fmt.Fprintf(&b, "  duration: /%s/,\n\n", reDuration)

	b.WriteString("  // A string escape sequence; grammar.js builds the surrounding string rule.\n")
	fmt.Fprintf(&b, "  escape: /%s/,\n\n", reEscape)

	b.WriteString("  // Comment markers; grammar.js builds the trivia (extras) rules from them.\n")
	b.WriteString("  comment: {\n")
	fmt.Fprintf(&b, "    line: %q,\n", token.LineCommentPrefix)
	fmt.Fprintf(&b, "    doc: %q,\n", token.DocCommentPrefix)
	fmt.Fprintf(&b, "    blockOpen: %q,\n", token.BlockCommentOpen)
	fmt.Fprintf(&b, "    blockClose: %q,\n", token.BlockCommentClose)
	b.WriteString("  },\n")

	b.WriteString("};\n")
	return b.String()
}
