// Code generated by "go generate"; DO NOT EDIT.

package concrete

import (
	"fmt"

	"github.com/masterbelt/masterbelt/pkg/diagnostic"
)

const (
	CodeArrowBlockBody     diagnostic.Code = "belt.parser.concrete.arrow_block_body"
	CodeExpectedAssign     diagnostic.Code = "belt.parser.concrete.expected_assign"
	CodeExpectedConst      diagnostic.Code = "belt.parser.concrete.expected_const"
	CodeExpectedExpression diagnostic.Code = "belt.parser.concrete.expected_expression"
	CodeExpectedFn         diagnostic.Code = "belt.parser.concrete.expected_fn"
	CodeExpectedFrom       diagnostic.Code = "belt.parser.concrete.expected_from"
	CodeExpectedFuncBody   diagnostic.Code = "belt.parser.concrete.expected_func_body"
	CodeExpectedIdentifier diagnostic.Code = "belt.parser.concrete.expected_identifier"
	CodeExpectedOperand    diagnostic.Code = "belt.parser.concrete.expected_operand"
	CodeExpectedParamList  diagnostic.Code = "belt.parser.concrete.expected_param_list"
	CodeExpectedPath       diagnostic.Code = "belt.parser.concrete.expected_path"
	CodeExpectedType       diagnostic.Code = "belt.parser.concrete.expected_type"
	CodeUnexpectedToken    diagnostic.Code = "belt.parser.concrete.unexpected_token"
)

func newArrowBlockBodyDiagnostic(offset int, width int) diagnostic.Diagnostic {
	return diagnostic.Diagnostic{
		Severity: diagnostic.Error,
		Code:     CodeArrowBlockBody,
		Message:  diagnostic.Render(diagnostic.DefaultLocale, CodeArrowBlockBody, nil),
		Fields:   nil,
		Offset:   offset,
		Width:    width,
	}
}

func newExpectedAssignDiagnostic(offset int, width int) diagnostic.Diagnostic {
	return diagnostic.Diagnostic{
		Severity: diagnostic.Error,
		Code:     CodeExpectedAssign,
		Message:  diagnostic.Render(diagnostic.DefaultLocale, CodeExpectedAssign, nil),
		Fields:   nil,
		Offset:   offset,
		Width:    width,
	}
}

func newExpectedConstDiagnostic(offset int, width int) diagnostic.Diagnostic {
	return diagnostic.Diagnostic{
		Severity: diagnostic.Error,
		Code:     CodeExpectedConst,
		Message:  diagnostic.Render(diagnostic.DefaultLocale, CodeExpectedConst, nil),
		Fields:   nil,
		Offset:   offset,
		Width:    width,
	}
}

func newExpectedExpressionDiagnostic(offset int, width int) diagnostic.Diagnostic {
	return diagnostic.Diagnostic{
		Severity: diagnostic.Error,
		Code:     CodeExpectedExpression,
		Message:  diagnostic.Render(diagnostic.DefaultLocale, CodeExpectedExpression, nil),
		Fields:   nil,
		Offset:   offset,
		Width:    width,
	}
}

func newExpectedFnDiagnostic(offset int, width int) diagnostic.Diagnostic {
	return diagnostic.Diagnostic{
		Severity: diagnostic.Error,
		Code:     CodeExpectedFn,
		Message:  diagnostic.Render(diagnostic.DefaultLocale, CodeExpectedFn, nil),
		Fields:   nil,
		Offset:   offset,
		Width:    width,
	}
}

func newExpectedFromDiagnostic(offset int, width int) diagnostic.Diagnostic {
	return diagnostic.Diagnostic{
		Severity: diagnostic.Error,
		Code:     CodeExpectedFrom,
		Message:  diagnostic.Render(diagnostic.DefaultLocale, CodeExpectedFrom, nil),
		Fields:   nil,
		Offset:   offset,
		Width:    width,
	}
}

func newExpectedFuncBodyDiagnostic(offset int, width int) diagnostic.Diagnostic {
	return diagnostic.Diagnostic{
		Severity: diagnostic.Error,
		Code:     CodeExpectedFuncBody,
		Message:  diagnostic.Render(diagnostic.DefaultLocale, CodeExpectedFuncBody, nil),
		Fields:   nil,
		Offset:   offset,
		Width:    width,
	}
}

func newExpectedIdentifierDiagnostic(offset int, width int) diagnostic.Diagnostic {
	return diagnostic.Diagnostic{
		Severity: diagnostic.Error,
		Code:     CodeExpectedIdentifier,
		Message:  diagnostic.Render(diagnostic.DefaultLocale, CodeExpectedIdentifier, nil),
		Fields:   nil,
		Offset:   offset,
		Width:    width,
	}
}

func newExpectedOperandDiagnostic(offset int, width int, operator string) diagnostic.Diagnostic {
	fields := map[string]fmt.Stringer{
		"operator": diagnostic.Str(operator),
	}
	return diagnostic.Diagnostic{
		Severity: diagnostic.Error,
		Code:     CodeExpectedOperand,
		Message:  diagnostic.Render(diagnostic.DefaultLocale, CodeExpectedOperand, fields),
		Fields:   fields,
		Offset:   offset,
		Width:    width,
	}
}

func newExpectedParamListDiagnostic(offset int, width int) diagnostic.Diagnostic {
	return diagnostic.Diagnostic{
		Severity: diagnostic.Error,
		Code:     CodeExpectedParamList,
		Message:  diagnostic.Render(diagnostic.DefaultLocale, CodeExpectedParamList, nil),
		Fields:   nil,
		Offset:   offset,
		Width:    width,
	}
}

func newExpectedPathDiagnostic(offset int, width int) diagnostic.Diagnostic {
	return diagnostic.Diagnostic{
		Severity: diagnostic.Error,
		Code:     CodeExpectedPath,
		Message:  diagnostic.Render(diagnostic.DefaultLocale, CodeExpectedPath, nil),
		Fields:   nil,
		Offset:   offset,
		Width:    width,
	}
}

func newExpectedTypeDiagnostic(offset int, width int) diagnostic.Diagnostic {
	return diagnostic.Diagnostic{
		Severity: diagnostic.Error,
		Code:     CodeExpectedType,
		Message:  diagnostic.Render(diagnostic.DefaultLocale, CodeExpectedType, nil),
		Fields:   nil,
		Offset:   offset,
		Width:    width,
	}
}

func newUnexpectedTokenDiagnostic(offset int, width int, kind string) diagnostic.Diagnostic {
	fields := map[string]fmt.Stringer{
		"kind": diagnostic.Str(kind),
	}
	return diagnostic.Diagnostic{
		Severity: diagnostic.Error,
		Code:     CodeUnexpectedToken,
		Message:  diagnostic.Render(diagnostic.DefaultLocale, CodeUnexpectedToken, fields),
		Fields:   fields,
		Offset:   offset,
		Width:    width,
	}
}
