// Code generated by "go generate"; DO NOT EDIT.

package lint

import (
	"github.com/masterbelt/masterbelt/pkg/diagnostic"
)

const (
	CodeUnreachableCode diagnostic.Code = "belt.lint.unreachable_code"
)

func newUnreachableCodeDiagnostic(offset int, width int) diagnostic.Diagnostic {
	return diagnostic.Diagnostic{
		Severity: diagnostic.Hint,
		Code:     CodeUnreachableCode,
		Message:  diagnostic.Render(diagnostic.DefaultLocale, CodeUnreachableCode, nil),
		Fields:   nil,
		Offset:   offset,
		Width:    width,
	}
}
