// Code generated by "go generate"; DO NOT EDIT.

package concrete

import (
	"fmt"

	"github.com/masterbelt/masterbelt/pkg/masterbelt/diagnostic"
)

const (
	CodeExpectedAssign     diagnostic.Code = "masterbelt.parser.concrete.expected_assign"
	CodeExpectedConst      diagnostic.Code = "masterbelt.parser.concrete.expected_const"
	CodeExpectedExpression diagnostic.Code = "masterbelt.parser.concrete.expected_expression"
	CodeExpectedIdentifier diagnostic.Code = "masterbelt.parser.concrete.expected_identifier"
	CodeExpectedType       diagnostic.Code = "masterbelt.parser.concrete.expected_type"
	CodeUnexpectedToken    diagnostic.Code = "masterbelt.parser.concrete.unexpected_token"
)

func newExpectedAssignDiagnostic(offset int, width int) diagnostic.Diagnostic {
	return diagnostic.Diagnostic{
		Severity: diagnostic.Error,
		Code:     CodeExpectedAssign,
		Message:  diagnostic.Render(diagnostic.DefaultLocale, CodeExpectedAssign, nil),
		Fields:   nil,
		Offset:   offset,
		Width:    width,
	}
}

func newExpectedConstDiagnostic(offset int, width int) diagnostic.Diagnostic {
	return diagnostic.Diagnostic{
		Severity: diagnostic.Error,
		Code:     CodeExpectedConst,
		Message:  diagnostic.Render(diagnostic.DefaultLocale, CodeExpectedConst, nil),
		Fields:   nil,
		Offset:   offset,
		Width:    width,
	}
}

func newExpectedExpressionDiagnostic(offset int, width int) diagnostic.Diagnostic {
	return diagnostic.Diagnostic{
		Severity: diagnostic.Error,
		Code:     CodeExpectedExpression,
		Message:  diagnostic.Render(diagnostic.DefaultLocale, CodeExpectedExpression, nil),
		Fields:   nil,
		Offset:   offset,
		Width:    width,
	}
}

func newExpectedIdentifierDiagnostic(offset int, width int) diagnostic.Diagnostic {
	return diagnostic.Diagnostic{
		Severity: diagnostic.Error,
		Code:     CodeExpectedIdentifier,
		Message:  diagnostic.Render(diagnostic.DefaultLocale, CodeExpectedIdentifier, nil),
		Fields:   nil,
		Offset:   offset,
		Width:    width,
	}
}

func newExpectedTypeDiagnostic(offset int, width int) diagnostic.Diagnostic {
	return diagnostic.Diagnostic{
		Severity: diagnostic.Error,
		Code:     CodeExpectedType,
		Message:  diagnostic.Render(diagnostic.DefaultLocale, CodeExpectedType, nil),
		Fields:   nil,
		Offset:   offset,
		Width:    width,
	}
}

func newUnexpectedTokenDiagnostic(offset int, width int, kind string) diagnostic.Diagnostic {
	fields := map[string]fmt.Stringer{
		"kind": diagnostic.Str(kind),
	}
	return diagnostic.Diagnostic{
		Severity: diagnostic.Error,
		Code:     CodeUnexpectedToken,
		Message:  diagnostic.Render(diagnostic.DefaultLocale, CodeUnexpectedToken, fields),
		Fields:   fields,
		Offset:   offset,
		Width:    width,
	}
}
