// Code generated by "go generate"; DO NOT EDIT.

package diagnostic

import "fmt"

// renderers maps each diagnostic code to a function that renders its message
// in a given locale from the diagnostic's fields.
var renderers = map[Code]func(Locale, map[string]fmt.Stringer) string{
	"masterbelt.lexer.invalid_escape": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return "不正なエスケープシーケンス: " + f["escape"].String()
		default:
			return "invalid escape sequence: " + f["escape"].String()
		}
	},
	"masterbelt.lexer.invalid_unicode_escape": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return "不正なUnicodeエスケープ: " + f["escape"].String()
		default:
			return "invalid unicode escape: " + f["escape"].String()
		}
	},
	"masterbelt.lexer.unexpected_character": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return "予期しない文字: " + f["char"].String()
		default:
			return "unexpected character: " + f["char"].String()
		}
	},
	"masterbelt.lexer.unterminated_block_comment": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return "ブロックコメントが閉じられていません"
		default:
			return "unterminated block comment"
		}
	},
	"masterbelt.lexer.unterminated_string": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return "文字列リテラルが閉じられていません"
		default:
			return "unterminated string literal"
		}
	},
	"masterbelt.parser.concrete.expected_assign": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return "'=' が必要です"
		default:
			return "expected '='"
		}
	},
	"masterbelt.parser.concrete.expected_const": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return "'const' が必要です"
		default:
			return "expected 'const'"
		}
	},
	"masterbelt.parser.concrete.expected_expression": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return "式が必要です"
		default:
			return "expected expression"
		}
	},
	"masterbelt.parser.concrete.expected_identifier": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return "識別子が必要です"
		default:
			return "expected identifier"
		}
	},
	"masterbelt.parser.concrete.expected_operand": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return "'" + f["operator"].String() + "' の後にオペランドが必要です"
		default:
			return "expected operand after '" + f["operator"].String() + "'"
		}
	},
	"masterbelt.parser.concrete.expected_type": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return "型が必要です"
		default:
			return "expected type"
		}
	},
	"masterbelt.parser.concrete.unexpected_token": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return "予期しないトークン: " + f["kind"].String()
		default:
			return "unexpected token: " + f["kind"].String()
		}
	},
	"masterbelt.semantic.constant_overflow": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return "定数 " + f["value"].String() + " は " + f["typ"].String() + " に収まりません"
		default:
			return "constant " + f["value"].String() + " overflows " + f["typ"].String()
		}
	},
	"masterbelt.semantic.cyclic_reference": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return f["name"].String() + " を含む循環参照です"
		default:
			return "cyclic reference involving " + f["name"].String()
		}
	},
	"masterbelt.semantic.division_by_zero": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return "ゼロ除算です"
		default:
			return "division by zero"
		}
	},
	"masterbelt.semantic.duplicate_declaration": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return f["name"].String() + " が重複して宣言されています"
		default:
			return "duplicate declaration of " + f["name"].String()
		}
	},
	"masterbelt.semantic.invalid_operation": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return "メソッド " + f["method"].String() + " を " + f["types"].String() + " に適用できません"
		default:
			return "cannot apply method " + f["method"].String() + " to " + f["types"].String()
		}
	},
	"masterbelt.semantic.type_mismatch": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return f["actual"].String() + " を " + f["expected"].String() + " として使えません"
		default:
			return "cannot use " + f["actual"].String() + " as " + f["expected"].String()
		}
	},
	"masterbelt.semantic.undefined_name": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return "未定義の名前: " + f["name"].String()
		default:
			return "undefined name: " + f["name"].String()
		}
	},
	"masterbelt.semantic.uninferable_collection": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return "このコレクションリテラルの型を推論できません。型注釈を付けてください"
		default:
			return "cannot infer the type of this collection literal; annotate it"
		}
	},
	"masterbelt.semantic.unknown_type": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return "未知の型: " + f["name"].String()
		default:
			return "unknown type: " + f["name"].String()
		}
	},
}
