// Code generated by "go generate"; DO NOT EDIT.

package diagnostic

import "fmt"

// renderers maps each diagnostic code to a function that renders its message
// in a given locale from the diagnostic's fields.
var renderers = map[Code]func(Locale, map[string]fmt.Stringer) string{
	"masterbelt.lexer.unexpected_character": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return "予期しない文字: " + f["char"].String()
		default:
			return "unexpected character: " + f["char"].String()
		}
	},
	"masterbelt.lexer.unterminated_block_comment": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return "ブロックコメントが閉じられていません"
		default:
			return "unterminated block comment"
		}
	},
	"masterbelt.parser.concrete.expected_assign": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return "'=' が必要です"
		default:
			return "expected '='"
		}
	},
	"masterbelt.parser.concrete.expected_const": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return "'const' が必要です"
		default:
			return "expected 'const'"
		}
	},
	"masterbelt.parser.concrete.expected_expression": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return "式が必要です"
		default:
			return "expected expression"
		}
	},
	"masterbelt.parser.concrete.expected_identifier": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return "識別子が必要です"
		default:
			return "expected identifier"
		}
	},
	"masterbelt.parser.concrete.expected_type": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return "型が必要です"
		default:
			return "expected type"
		}
	},
	"masterbelt.parser.concrete.unexpected_token": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return "予期しないトークン: " + f["kind"].String()
		default:
			return "unexpected token: " + f["kind"].String()
		}
	},
}
