// Code generated by "go generate"; DO NOT EDIT.

package diagnostic

import "fmt"

// renderers maps each diagnostic code to a function that renders its message
// in a given locale from the diagnostic's fields.
var renderers = map[Code]func(Locale, map[string]fmt.Stringer) string{
	"masterbelt.lexer.unexpected_character": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return "予期しない文字: " + f["char"].String()
		default:
			return "unexpected character: " + f["char"].String()
		}
	},
	"masterbelt.lexer.unterminated_block_comment": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return "ブロックコメントが閉じられていません"
		default:
			return "unterminated block comment"
		}
	},
}
