// Code generated by "go generate"; DO NOT EDIT.

package config

import (
	"fmt"

	"github.com/masterbelt/masterbelt/pkg/diagnostic"
)

const (
	CodeEntryNotFound        diagnostic.Code = "project.config.entry_not_found"
	CodeInvalid              diagnostic.Code = "project.config.invalid"
	CodeMissing              diagnostic.Code = "project.config.missing"
	CodeMissingEntry         diagnostic.Code = "project.config.missing_entry"
	CodeProfileEntryNotFound diagnostic.Code = "project.config.profile_entry_not_found"
	CodeProfileMissingEntry  diagnostic.Code = "project.config.profile_missing_entry"
	CodeUnknownProfile       diagnostic.Code = "project.config.unknown_profile"
)

func newEntryNotFoundDiagnostic(offset int, width int, path string) diagnostic.Diagnostic {
	fields := map[string]fmt.Stringer{
		"path": diagnostic.Str(path),
	}
	return diagnostic.Diagnostic{
		Severity: diagnostic.Error,
		Code:     CodeEntryNotFound,
		Message:  diagnostic.Render(diagnostic.DefaultLocale, CodeEntryNotFound, fields),
		Fields:   fields,
		Offset:   offset,
		Width:    width,
	}
}

func newInvalidDiagnostic(offset int, width int, detail string) diagnostic.Diagnostic {
	fields := map[string]fmt.Stringer{
		"detail": diagnostic.Str(detail),
	}
	return diagnostic.Diagnostic{
		Severity: diagnostic.Error,
		Code:     CodeInvalid,
		Message:  diagnostic.Render(diagnostic.DefaultLocale, CodeInvalid, fields),
		Fields:   fields,
		Offset:   offset,
		Width:    width,
	}
}

func newMissingDiagnostic(offset int, width int) diagnostic.Diagnostic {
	return diagnostic.Diagnostic{
		Severity: diagnostic.Error,
		Code:     CodeMissing,
		Message:  diagnostic.Render(diagnostic.DefaultLocale, CodeMissing, nil),
		Fields:   nil,
		Offset:   offset,
		Width:    width,
	}
}

func newMissingEntryDiagnostic(offset int, width int) diagnostic.Diagnostic {
	return diagnostic.Diagnostic{
		Severity: diagnostic.Error,
		Code:     CodeMissingEntry,
		Message:  diagnostic.Render(diagnostic.DefaultLocale, CodeMissingEntry, nil),
		Fields:   nil,
		Offset:   offset,
		Width:    width,
	}
}

func newProfileEntryNotFoundDiagnostic(offset int, width int, profile string, path string) diagnostic.Diagnostic {
	fields := map[string]fmt.Stringer{
		"profile": diagnostic.Str(profile),
		"path":    diagnostic.Str(path),
	}
	return diagnostic.Diagnostic{
		Severity: diagnostic.Error,
		Code:     CodeProfileEntryNotFound,
		Message:  diagnostic.Render(diagnostic.DefaultLocale, CodeProfileEntryNotFound, fields),
		Fields:   fields,
		Offset:   offset,
		Width:    width,
	}
}

func newProfileMissingEntryDiagnostic(offset int, width int, profile string) diagnostic.Diagnostic {
	fields := map[string]fmt.Stringer{
		"profile": diagnostic.Str(profile),
	}
	return diagnostic.Diagnostic{
		Severity: diagnostic.Error,
		Code:     CodeProfileMissingEntry,
		Message:  diagnostic.Render(diagnostic.DefaultLocale, CodeProfileMissingEntry, fields),
		Fields:   fields,
		Offset:   offset,
		Width:    width,
	}
}

func newUnknownProfileDiagnostic(offset int, width int, profile string) diagnostic.Diagnostic {
	fields := map[string]fmt.Stringer{
		"profile": diagnostic.Str(profile),
	}
	return diagnostic.Diagnostic{
		Severity: diagnostic.Error,
		Code:     CodeUnknownProfile,
		Message:  diagnostic.Render(diagnostic.DefaultLocale, CodeUnknownProfile, fields),
		Fields:   fields,
		Offset:   offset,
		Width:    width,
	}
}
