// Code generated by "go generate"; DO NOT EDIT.

package config

import (
	"fmt"

	"github.com/masterbelt/masterbelt/pkg/diagnostic"
)

const (
	CodeEntryNotFound diagnostic.Code = "project.config.entry_not_found"
	CodeInvalid       diagnostic.Code = "project.config.invalid"
	CodeMissing       diagnostic.Code = "project.config.missing"
	CodeMissingEntry  diagnostic.Code = "project.config.missing_entry"
)

func newEntryNotFoundDiagnostic(offset int, width int, path string) diagnostic.Diagnostic {
	fields := map[string]fmt.Stringer{
		"path": diagnostic.Str(path),
	}
	return diagnostic.Diagnostic{
		Severity: diagnostic.Error,
		Code:     CodeEntryNotFound,
		Message:  diagnostic.Render(diagnostic.DefaultLocale, CodeEntryNotFound, fields),
		Fields:   fields,
		Offset:   offset,
		Width:    width,
	}
}

func newInvalidDiagnostic(offset int, width int, detail string) diagnostic.Diagnostic {
	fields := map[string]fmt.Stringer{
		"detail": diagnostic.Str(detail),
	}
	return diagnostic.Diagnostic{
		Severity: diagnostic.Error,
		Code:     CodeInvalid,
		Message:  diagnostic.Render(diagnostic.DefaultLocale, CodeInvalid, fields),
		Fields:   fields,
		Offset:   offset,
		Width:    width,
	}
}

func newMissingDiagnostic(offset int, width int) diagnostic.Diagnostic {
	return diagnostic.Diagnostic{
		Severity: diagnostic.Error,
		Code:     CodeMissing,
		Message:  diagnostic.Render(diagnostic.DefaultLocale, CodeMissing, nil),
		Fields:   nil,
		Offset:   offset,
		Width:    width,
	}
}

func newMissingEntryDiagnostic(offset int, width int) diagnostic.Diagnostic {
	return diagnostic.Diagnostic{
		Severity: diagnostic.Error,
		Code:     CodeMissingEntry,
		Message:  diagnostic.Render(diagnostic.DefaultLocale, CodeMissingEntry, nil),
		Fields:   nil,
		Offset:   offset,
		Width:    width,
	}
}
