// Code generated by "go generate"; DO NOT EDIT.

package semantic

import (
	"fmt"

	"github.com/masterbelt/masterbelt/pkg/diagnostic"
)

const (
	CodeAccessorCollision          diagnostic.Code = "belt.semantic.accessor_collision"
	CodeAmbiguousFuncOverload      diagnostic.Code = "belt.semantic.ambiguous_func_overload"
	CodeAmbiguousImport            diagnostic.Code = "belt.semantic.ambiguous_import"
	CodeAmbiguousOverload          diagnostic.Code = "belt.semantic.ambiguous_overload"
	CodeAmbiguousUnionMember       diagnostic.Code = "belt.semantic.ambiguous_union_member"
	CodeArityMismatch              diagnostic.Code = "belt.semantic.arity_mismatch"
	CodeArmTypeNotInUnion          diagnostic.Code = "belt.semantic.arm_type_not_in_union"
	CodeArmValueTypeMismatch       diagnostic.Code = "belt.semantic.arm_value_type_mismatch"
	CodeAssertionFailed            diagnostic.Code = "belt.semantic.assertion_failed"
	CodeAssertionNotBool           diagnostic.Code = "belt.semantic.assertion_not_bool"
	CodeAssertionNotConstant       diagnostic.Code = "belt.semantic.assertion_not_constant"
	CodeAssignToConst              diagnostic.Code = "belt.semantic.assign_to_const"
	CodeAssignToUndefined          diagnostic.Code = "belt.semantic.assign_to_undefined"
	CodeAssignTypeMismatch         diagnostic.Code = "belt.semantic.assign_type_mismatch"
	CodeBoundNotSatisfied          diagnostic.Code = "belt.semantic.bound_not_satisfied"
	CodeBuiltinOutsideBuiltin      diagnostic.Code = "belt.semantic.builtin_outside_builtin"
	CodeConditionNotBool           diagnostic.Code = "belt.semantic.condition_not_bool"
	CodeConstantOverflow           diagnostic.Code = "belt.semantic.constant_overflow"
	CodeCyclicModule               diagnostic.Code = "belt.semantic.cyclic_module"
	CodeCyclicReference            diagnostic.Code = "belt.semantic.cyclic_reference"
	CodeDivisionByZero             diagnostic.Code = "belt.semantic.division_by_zero"
	CodeDuplicateDeclaration       diagnostic.Code = "belt.semantic.duplicate_declaration"
	CodeDuplicateEnumMember        diagnostic.Code = "belt.semantic.duplicate_enum_member"
	CodeDuplicateEnumValue         diagnostic.Code = "belt.semantic.duplicate_enum_value"
	CodeDuplicateFuncOverload      diagnostic.Code = "belt.semantic.duplicate_func_overload"
	CodeDuplicateMatchArm          diagnostic.Code = "belt.semantic.duplicate_match_arm"
	CodeDuplicateOverload          diagnostic.Code = "belt.semantic.duplicate_overload"
	CodeDuplicateSwitchArm         diagnostic.Code = "belt.semantic.duplicate_switch_arm"
	CodeEffectInPureContext        diagnostic.Code = "belt.semantic.effect_in_pure_context"
	CodeExternOutsideBuiltin       diagnostic.Code = "belt.semantic.extern_outside_builtin"
	CodeGenericStatic              diagnostic.Code = "belt.semantic.generic_static"
	CodeImmutableData              diagnostic.Code = "belt.semantic.immutable_data"
	CodeIndexOutOfRange            diagnostic.Code = "belt.semantic.index_out_of_range"
	CodeInterfaceMemberConflict    diagnostic.Code = "belt.semantic.interface_member_conflict"
	CodeInterfaceMemberOverride    diagnostic.Code = "belt.semantic.interface_member_override"
	CodeInvalidEnumBaseType        diagnostic.Code = "belt.semantic.invalid_enum_base_type"
	CodeInvalidGetterSignature     diagnostic.Code = "belt.semantic.invalid_getter_signature"
	CodeInvalidOperation           diagnostic.Code = "belt.semantic.invalid_operation"
	CodeInvalidSetterSignature     diagnostic.Code = "belt.semantic.invalid_setter_signature"
	CodeLambdaArityMismatch        diagnostic.Code = "belt.semantic.lambda_arity_mismatch"
	CodeLoopVarImmutable           diagnostic.Code = "belt.semantic.loop_var_immutable"
	CodeMasterDuplicatePrimaryKey  diagnostic.Code = "belt.semantic.master_duplicate_primary_key"
	CodeMasterMissingPrimary       diagnostic.Code = "belt.semantic.master_missing_primary"
	CodeMasterMissingRow           diagnostic.Code = "belt.semantic.master_missing_row"
	CodeMasterPrimaryUnknownField  diagnostic.Code = "belt.semantic.master_primary_unknown_field"
	CodeMasterWhereUnsupported     diagnostic.Code = "belt.semantic.master_where_unsupported"
	CodeMissingEffect              diagnostic.Code = "belt.semantic.missing_effect"
	CodeMissingField               diagnostic.Code = "belt.semantic.missing_field"
	CodeMissingInitializer         diagnostic.Code = "belt.semantic.missing_initializer"
	CodeMissingRequiredMethod      diagnostic.Code = "belt.semantic.missing_required_method"
	CodeMissingReturn              diagnostic.Code = "belt.semantic.missing_return"
	CodeNoMatchingFuncOverload     diagnostic.Code = "belt.semantic.no_matching_func_overload"
	CodeNoMatchingOverload         diagnostic.Code = "belt.semantic.no_matching_overload"
	CodeNoMethodOnUnboundedTypevar diagnostic.Code = "belt.semantic.no_method_on_unbounded_typevar"
	CodeNonExhaustiveMatch         diagnostic.Code = "belt.semantic.non_exhaustive_match"
	CodeNonExhaustiveSwitch        diagnostic.Code = "belt.semantic.non_exhaustive_switch"
	CodeNotARecord                 diagnostic.Code = "belt.semantic.not_a_record"
	CodeNotAnInterface             diagnostic.Code = "belt.semantic.not_an_interface"
	CodeNotExported                diagnostic.Code = "belt.semantic.not_exported"
	CodeNotIterable                diagnostic.Code = "belt.semantic.not_iterable"
	CodeRangeStepZero              diagnostic.Code = "belt.semantic.range_step_zero"
	CodeRefinementNotBool          diagnostic.Code = "belt.semantic.refinement_not_bool"
	CodeRefinementNotConstant      diagnostic.Code = "belt.semantic.refinement_not_constant"
	CodeRefinementViolation        diagnostic.Code = "belt.semantic.refinement_violation"
	CodeScrutineeNotComparable     diagnostic.Code = "belt.semantic.scrutinee_not_comparable"
	CodeSelfOutsideMethod          diagnostic.Code = "belt.semantic.self_outside_method"
	CodeStaticCollision            diagnostic.Code = "belt.semantic.static_collision"
	CodeTernaryBranchMismatch      diagnostic.Code = "belt.semantic.ternary_branch_mismatch"
	CodeTernaryConditionNotBool    diagnostic.Code = "belt.semantic.ternary_condition_not_bool"
	CodeTypeMismatch               diagnostic.Code = "belt.semantic.type_mismatch"
	CodeUndefinedName              diagnostic.Code = "belt.semantic.undefined_name"
	CodeUnfoldedConst              diagnostic.Code = "belt.semantic.unfolded_const"
	CodeUninferableCollection      diagnostic.Code = "belt.semantic.uninferable_collection"
	CodeUninferableParameter       diagnostic.Code = "belt.semantic.uninferable_parameter"
	CodeUninferableRecord          diagnostic.Code = "belt.semantic.uninferable_record"
	CodeUninferableResult          diagnostic.Code = "belt.semantic.uninferable_result"
	CodeUninferableTypeParam       diagnostic.Code = "belt.semantic.uninferable_type_param"
	CodeUnknownAssociatedConst     diagnostic.Code = "belt.semantic.unknown_associated_const"
	CodeUnknownEnumMember          diagnostic.Code = "belt.semantic.unknown_enum_member"
	CodeUnknownField               diagnostic.Code = "belt.semantic.unknown_field"
	CodeUnknownMember              diagnostic.Code = "belt.semantic.unknown_member"
	CodeUnknownStatic              diagnostic.Code = "belt.semantic.unknown_static"
	CodeUnknownType                diagnostic.Code = "belt.semantic.unknown_type"
	CodeUnreachableArm             diagnostic.Code = "belt.semantic.unreachable_arm"
	CodeUnusedEffect               diagnostic.Code = "belt.semantic.unused_effect"
	CodeUseNotFound                diagnostic.Code = "belt.semantic.use_not_found"
)

func newAccessorCollisionDiagnostic(offset int, width int, name string, typ string) diagnostic.Diagnostic {
	fields := map[string]fmt.Stringer{
		"name": diagnostic.Str(name),
		"typ":  diagnostic.Str(typ),
	}
	return diagnostic.Diagnostic{
		Severity: diagnostic.Error,
		Code:     CodeAccessorCollision,
		Message:  diagnostic.Render(diagnostic.DefaultLocale, CodeAccessorCollision, fields),
		Fields:   fields,
		Offset:   offset,
		Width:    width,
	}
}

func newAmbiguousFuncOverloadDiagnostic(offset int, width int, name string, types string) diagnostic.Diagnostic {
	fields := map[string]fmt.Stringer{
		"name":  diagnostic.Str(name),
		"types": diagnostic.Str(types),
	}
	return diagnostic.Diagnostic{
		Severity: diagnostic.Error,
		Code:     CodeAmbiguousFuncOverload,
		Message:  diagnostic.Render(diagnostic.DefaultLocale, CodeAmbiguousFuncOverload, fields),
		Fields:   fields,
		Offset:   offset,
		Width:    width,
	}
}

func newAmbiguousImportDiagnostic(offset int, width int, name string) diagnostic.Diagnostic {
	fields := map[string]fmt.Stringer{
		"name": diagnostic.Str(name),
	}
	return diagnostic.Diagnostic{
		Severity: diagnostic.Error,
		Code:     CodeAmbiguousImport,
		Message:  diagnostic.Render(diagnostic.DefaultLocale, CodeAmbiguousImport, fields),
		Fields:   fields,
		Offset:   offset,
		Width:    width,
	}
}

func newAmbiguousOverloadDiagnostic(offset int, width int, method string, types string) diagnostic.Diagnostic {
	fields := map[string]fmt.Stringer{
		"method": diagnostic.Str(method),
		"types":  diagnostic.Str(types),
	}
	return diagnostic.Diagnostic{
		Severity: diagnostic.Error,
		Code:     CodeAmbiguousOverload,
		Message:  diagnostic.Render(diagnostic.DefaultLocale, CodeAmbiguousOverload, fields),
		Fields:   fields,
		Offset:   offset,
		Width:    width,
	}
}

func newAmbiguousUnionMemberDiagnostic(offset int, width int, actual string, typ string) diagnostic.Diagnostic {
	fields := map[string]fmt.Stringer{
		"actual": diagnostic.Str(actual),
		"typ":    diagnostic.Str(typ),
	}
	return diagnostic.Diagnostic{
		Severity: diagnostic.Error,
		Code:     CodeAmbiguousUnionMember,
		Message:  diagnostic.Render(diagnostic.DefaultLocale, CodeAmbiguousUnionMember, fields),
		Fields:   fields,
		Offset:   offset,
		Width:    width,
	}
}

func newArityMismatchDiagnostic(offset int, width int, name string, actual int, expected int) diagnostic.Diagnostic {
	fields := map[string]fmt.Stringer{
		"name":     diagnostic.Str(name),
		"actual":   diagnostic.Int(actual),
		"expected": diagnostic.Int(expected),
	}
	return diagnostic.Diagnostic{
		Severity: diagnostic.Error,
		Code:     CodeArityMismatch,
		Message:  diagnostic.Render(diagnostic.DefaultLocale, CodeArityMismatch, fields),
		Fields:   fields,
		Offset:   offset,
		Width:    width,
	}
}

func newArmTypeNotInUnionDiagnostic(offset int, width int, arm string, typ string) diagnostic.Diagnostic {
	fields := map[string]fmt.Stringer{
		"arm": diagnostic.Str(arm),
		"typ": diagnostic.Str(typ),
	}
	return diagnostic.Diagnostic{
		Severity: diagnostic.Error,
		Code:     CodeArmTypeNotInUnion,
		Message:  diagnostic.Render(diagnostic.DefaultLocale, CodeArmTypeNotInUnion, fields),
		Fields:   fields,
		Offset:   offset,
		Width:    width,
	}
}

func newArmValueTypeMismatchDiagnostic(offset int, width int, actual string, expected string) diagnostic.Diagnostic {
	fields := map[string]fmt.Stringer{
		"actual":   diagnostic.Str(actual),
		"expected": diagnostic.Str(expected),
	}
	return diagnostic.Diagnostic{
		Severity: diagnostic.Error,
		Code:     CodeArmValueTypeMismatch,
		Message:  diagnostic.Render(diagnostic.DefaultLocale, CodeArmValueTypeMismatch, fields),
		Fields:   fields,
		Offset:   offset,
		Width:    width,
	}
}

func newAssertionFailedDiagnostic(offset int, width int, cond string, doc string, diagram string) diagnostic.Diagnostic {
	fields := map[string]fmt.Stringer{
		"cond":    diagnostic.Str(cond),
		"doc":     diagnostic.Str(doc),
		"diagram": diagnostic.Str(diagram),
	}
	return diagnostic.Diagnostic{
		Severity: diagnostic.Error,
		Code:     CodeAssertionFailed,
		Message:  diagnostic.Render(diagnostic.DefaultLocale, CodeAssertionFailed, fields),
		Fields:   fields,
		Offset:   offset,
		Width:    width,
	}
}

func newAssertionNotBoolDiagnostic(offset int, width int, typ string) diagnostic.Diagnostic {
	fields := map[string]fmt.Stringer{
		"typ": diagnostic.Str(typ),
	}
	return diagnostic.Diagnostic{
		Severity: diagnostic.Error,
		Code:     CodeAssertionNotBool,
		Message:  diagnostic.Render(diagnostic.DefaultLocale, CodeAssertionNotBool, fields),
		Fields:   fields,
		Offset:   offset,
		Width:    width,
	}
}

func newAssertionNotConstantDiagnostic(offset int, width int) diagnostic.Diagnostic {
	return diagnostic.Diagnostic{
		Severity: diagnostic.Error,
		Code:     CodeAssertionNotConstant,
		Message:  diagnostic.Render(diagnostic.DefaultLocale, CodeAssertionNotConstant, nil),
		Fields:   nil,
		Offset:   offset,
		Width:    width,
	}
}

func newAssignToConstDiagnostic(offset int, width int, name string) diagnostic.Diagnostic {
	fields := map[string]fmt.Stringer{
		"name": diagnostic.Str(name),
	}
	return diagnostic.Diagnostic{
		Severity: diagnostic.Error,
		Code:     CodeAssignToConst,
		Message:  diagnostic.Render(diagnostic.DefaultLocale, CodeAssignToConst, fields),
		Fields:   fields,
		Offset:   offset,
		Width:    width,
	}
}

func newAssignToUndefinedDiagnostic(offset int, width int, name string) diagnostic.Diagnostic {
	fields := map[string]fmt.Stringer{
		"name": diagnostic.Str(name),
	}
	return diagnostic.Diagnostic{
		Severity: diagnostic.Error,
		Code:     CodeAssignToUndefined,
		Message:  diagnostic.Render(diagnostic.DefaultLocale, CodeAssignToUndefined, fields),
		Fields:   fields,
		Offset:   offset,
		Width:    width,
	}
}

func newAssignTypeMismatchDiagnostic(offset int, width int, name string, actual string, expected string) diagnostic.Diagnostic {
	fields := map[string]fmt.Stringer{
		"name":     diagnostic.Str(name),
		"actual":   diagnostic.Str(actual),
		"expected": diagnostic.Str(expected),
	}
	return diagnostic.Diagnostic{
		Severity: diagnostic.Error,
		Code:     CodeAssignTypeMismatch,
		Message:  diagnostic.Render(diagnostic.DefaultLocale, CodeAssignTypeMismatch, fields),
		Fields:   fields,
		Offset:   offset,
		Width:    width,
	}
}

func newBoundNotSatisfiedDiagnostic(offset int, width int, typ string, bound string) diagnostic.Diagnostic {
	fields := map[string]fmt.Stringer{
		"typ":   diagnostic.Str(typ),
		"bound": diagnostic.Str(bound),
	}
	return diagnostic.Diagnostic{
		Severity: diagnostic.Error,
		Code:     CodeBoundNotSatisfied,
		Message:  diagnostic.Render(diagnostic.DefaultLocale, CodeBoundNotSatisfied, fields),
		Fields:   fields,
		Offset:   offset,
		Width:    width,
	}
}

func newBuiltinOutsideBuiltinDiagnostic(offset int, width int, name string) diagnostic.Diagnostic {
	fields := map[string]fmt.Stringer{
		"name": diagnostic.Str(name),
	}
	return diagnostic.Diagnostic{
		Severity: diagnostic.Error,
		Code:     CodeBuiltinOutsideBuiltin,
		Message:  diagnostic.Render(diagnostic.DefaultLocale, CodeBuiltinOutsideBuiltin, fields),
		Fields:   fields,
		Offset:   offset,
		Width:    width,
	}
}

func newConditionNotBoolDiagnostic(offset int, width int, typ string) diagnostic.Diagnostic {
	fields := map[string]fmt.Stringer{
		"typ": diagnostic.Str(typ),
	}
	return diagnostic.Diagnostic{
		Severity: diagnostic.Error,
		Code:     CodeConditionNotBool,
		Message:  diagnostic.Render(diagnostic.DefaultLocale, CodeConditionNotBool, fields),
		Fields:   fields,
		Offset:   offset,
		Width:    width,
	}
}

func newConstantOverflowDiagnostic(offset int, width int, value string, typ string) diagnostic.Diagnostic {
	fields := map[string]fmt.Stringer{
		"value": diagnostic.Str(value),
		"typ":   diagnostic.Str(typ),
	}
	return diagnostic.Diagnostic{
		Severity: diagnostic.Error,
		Code:     CodeConstantOverflow,
		Message:  diagnostic.Render(diagnostic.DefaultLocale, CodeConstantOverflow, fields),
		Fields:   fields,
		Offset:   offset,
		Width:    width,
	}
}

func newCyclicModuleDiagnostic(offset int, width int, path string) diagnostic.Diagnostic {
	fields := map[string]fmt.Stringer{
		"path": diagnostic.Str(path),
	}
	return diagnostic.Diagnostic{
		Severity: diagnostic.Error,
		Code:     CodeCyclicModule,
		Message:  diagnostic.Render(diagnostic.DefaultLocale, CodeCyclicModule, fields),
		Fields:   fields,
		Offset:   offset,
		Width:    width,
	}
}

func newCyclicReferenceDiagnostic(offset int, width int, name string) diagnostic.Diagnostic {
	fields := map[string]fmt.Stringer{
		"name": diagnostic.Str(name),
	}
	return diagnostic.Diagnostic{
		Severity: diagnostic.Error,
		Code:     CodeCyclicReference,
		Message:  diagnostic.Render(diagnostic.DefaultLocale, CodeCyclicReference, fields),
		Fields:   fields,
		Offset:   offset,
		Width:    width,
	}
}

func newDivisionByZeroDiagnostic(offset int, width int) diagnostic.Diagnostic {
	return diagnostic.Diagnostic{
		Severity: diagnostic.Error,
		Code:     CodeDivisionByZero,
		Message:  diagnostic.Render(diagnostic.DefaultLocale, CodeDivisionByZero, nil),
		Fields:   nil,
		Offset:   offset,
		Width:    width,
	}
}

func newDuplicateDeclarationDiagnostic(offset int, width int, name string) diagnostic.Diagnostic {
	fields := map[string]fmt.Stringer{
		"name": diagnostic.Str(name),
	}
	return diagnostic.Diagnostic{
		Severity: diagnostic.Error,
		Code:     CodeDuplicateDeclaration,
		Message:  diagnostic.Render(diagnostic.DefaultLocale, CodeDuplicateDeclaration, fields),
		Fields:   fields,
		Offset:   offset,
		Width:    width,
	}
}

func newDuplicateEnumMemberDiagnostic(offset int, width int, name string) diagnostic.Diagnostic {
	fields := map[string]fmt.Stringer{
		"name": diagnostic.Str(name),
	}
	return diagnostic.Diagnostic{
		Severity: diagnostic.Error,
		Code:     CodeDuplicateEnumMember,
		Message:  diagnostic.Render(diagnostic.DefaultLocale, CodeDuplicateEnumMember, fields),
		Fields:   fields,
		Offset:   offset,
		Width:    width,
	}
}

func newDuplicateEnumValueDiagnostic(offset int, width int, name string, value string) diagnostic.Diagnostic {
	fields := map[string]fmt.Stringer{
		"name":  diagnostic.Str(name),
		"value": diagnostic.Str(value),
	}
	return diagnostic.Diagnostic{
		Severity: diagnostic.Error,
		Code:     CodeDuplicateEnumValue,
		Message:  diagnostic.Render(diagnostic.DefaultLocale, CodeDuplicateEnumValue, fields),
		Fields:   fields,
		Offset:   offset,
		Width:    width,
	}
}

func newDuplicateFuncOverloadDiagnostic(offset int, width int, name string, types string) diagnostic.Diagnostic {
	fields := map[string]fmt.Stringer{
		"name":  diagnostic.Str(name),
		"types": diagnostic.Str(types),
	}
	return diagnostic.Diagnostic{
		Severity: diagnostic.Error,
		Code:     CodeDuplicateFuncOverload,
		Message:  diagnostic.Render(diagnostic.DefaultLocale, CodeDuplicateFuncOverload, fields),
		Fields:   fields,
		Offset:   offset,
		Width:    width,
	}
}

func newDuplicateMatchArmDiagnostic(offset int, width int, arm string) diagnostic.Diagnostic {
	fields := map[string]fmt.Stringer{
		"arm": diagnostic.Str(arm),
	}
	return diagnostic.Diagnostic{
		Severity: diagnostic.Error,
		Code:     CodeDuplicateMatchArm,
		Message:  diagnostic.Render(diagnostic.DefaultLocale, CodeDuplicateMatchArm, fields),
		Fields:   fields,
		Offset:   offset,
		Width:    width,
	}
}

func newDuplicateOverloadDiagnostic(offset int, width int, method string, types string) diagnostic.Diagnostic {
	fields := map[string]fmt.Stringer{
		"method": diagnostic.Str(method),
		"types":  diagnostic.Str(types),
	}
	return diagnostic.Diagnostic{
		Severity: diagnostic.Error,
		Code:     CodeDuplicateOverload,
		Message:  diagnostic.Render(diagnostic.DefaultLocale, CodeDuplicateOverload, fields),
		Fields:   fields,
		Offset:   offset,
		Width:    width,
	}
}

func newDuplicateSwitchArmDiagnostic(offset int, width int, value string) diagnostic.Diagnostic {
	fields := map[string]fmt.Stringer{
		"value": diagnostic.Str(value),
	}
	return diagnostic.Diagnostic{
		Severity: diagnostic.Error,
		Code:     CodeDuplicateSwitchArm,
		Message:  diagnostic.Render(diagnostic.DefaultLocale, CodeDuplicateSwitchArm, fields),
		Fields:   fields,
		Offset:   offset,
		Width:    width,
	}
}

func newEffectInPureContextDiagnostic(offset int, width int, effect string, context string) diagnostic.Diagnostic {
	fields := map[string]fmt.Stringer{
		"effect":  diagnostic.Str(effect),
		"context": diagnostic.Str(context),
	}
	return diagnostic.Diagnostic{
		Severity: diagnostic.Error,
		Code:     CodeEffectInPureContext,
		Message:  diagnostic.Render(diagnostic.DefaultLocale, CodeEffectInPureContext, fields),
		Fields:   fields,
		Offset:   offset,
		Width:    width,
	}
}

func newExternOutsideBuiltinDiagnostic(offset int, width int, name string) diagnostic.Diagnostic {
	fields := map[string]fmt.Stringer{
		"name": diagnostic.Str(name),
	}
	return diagnostic.Diagnostic{
		Severity: diagnostic.Error,
		Code:     CodeExternOutsideBuiltin,
		Message:  diagnostic.Render(diagnostic.DefaultLocale, CodeExternOutsideBuiltin, fields),
		Fields:   fields,
		Offset:   offset,
		Width:    width,
	}
}

func newGenericStaticDiagnostic(offset int, width int, name string) diagnostic.Diagnostic {
	fields := map[string]fmt.Stringer{
		"name": diagnostic.Str(name),
	}
	return diagnostic.Diagnostic{
		Severity: diagnostic.Error,
		Code:     CodeGenericStatic,
		Message:  diagnostic.Render(diagnostic.DefaultLocale, CodeGenericStatic, fields),
		Fields:   fields,
		Offset:   offset,
		Width:    width,
	}
}

func newImmutableDataDiagnostic(offset int, width int) diagnostic.Diagnostic {
	return diagnostic.Diagnostic{
		Severity: diagnostic.Error,
		Code:     CodeImmutableData,
		Message:  diagnostic.Render(diagnostic.DefaultLocale, CodeImmutableData, nil),
		Fields:   nil,
		Offset:   offset,
		Width:    width,
	}
}

func newIndexOutOfRangeDiagnostic(offset int, width int, index string, length string) diagnostic.Diagnostic {
	fields := map[string]fmt.Stringer{
		"index":  diagnostic.Str(index),
		"length": diagnostic.Str(length),
	}
	return diagnostic.Diagnostic{
		Severity: diagnostic.Error,
		Code:     CodeIndexOutOfRange,
		Message:  diagnostic.Render(diagnostic.DefaultLocale, CodeIndexOutOfRange, fields),
		Fields:   fields,
		Offset:   offset,
		Width:    width,
	}
}

func newInterfaceMemberConflictDiagnostic(offset int, width int, child string, method string, first string, second string) diagnostic.Diagnostic {
	fields := map[string]fmt.Stringer{
		"child":  diagnostic.Str(child),
		"method": diagnostic.Str(method),
		"first":  diagnostic.Str(first),
		"second": diagnostic.Str(second),
	}
	return diagnostic.Diagnostic{
		Severity: diagnostic.Error,
		Code:     CodeInterfaceMemberConflict,
		Message:  diagnostic.Render(diagnostic.DefaultLocale, CodeInterfaceMemberConflict, fields),
		Fields:   fields,
		Offset:   offset,
		Width:    width,
	}
}

func newInterfaceMemberOverrideDiagnostic(offset int, width int, child string, method string, ancestor string) diagnostic.Diagnostic {
	fields := map[string]fmt.Stringer{
		"child":    diagnostic.Str(child),
		"method":   diagnostic.Str(method),
		"ancestor": diagnostic.Str(ancestor),
	}
	return diagnostic.Diagnostic{
		Severity: diagnostic.Error,
		Code:     CodeInterfaceMemberOverride,
		Message:  diagnostic.Render(diagnostic.DefaultLocale, CodeInterfaceMemberOverride, fields),
		Fields:   fields,
		Offset:   offset,
		Width:    width,
	}
}

func newInvalidEnumBaseTypeDiagnostic(offset int, width int, typ string) diagnostic.Diagnostic {
	fields := map[string]fmt.Stringer{
		"typ": diagnostic.Str(typ),
	}
	return diagnostic.Diagnostic{
		Severity: diagnostic.Error,
		Code:     CodeInvalidEnumBaseType,
		Message:  diagnostic.Render(diagnostic.DefaultLocale, CodeInvalidEnumBaseType, fields),
		Fields:   fields,
		Offset:   offset,
		Width:    width,
	}
}

func newInvalidGetterSignatureDiagnostic(offset int, width int, name string) diagnostic.Diagnostic {
	fields := map[string]fmt.Stringer{
		"name": diagnostic.Str(name),
	}
	return diagnostic.Diagnostic{
		Severity: diagnostic.Error,
		Code:     CodeInvalidGetterSignature,
		Message:  diagnostic.Render(diagnostic.DefaultLocale, CodeInvalidGetterSignature, fields),
		Fields:   fields,
		Offset:   offset,
		Width:    width,
	}
}

func newInvalidOperationDiagnostic(offset int, width int, method string, types string) diagnostic.Diagnostic {
	fields := map[string]fmt.Stringer{
		"method": diagnostic.Str(method),
		"types":  diagnostic.Str(types),
	}
	return diagnostic.Diagnostic{
		Severity: diagnostic.Error,
		Code:     CodeInvalidOperation,
		Message:  diagnostic.Render(diagnostic.DefaultLocale, CodeInvalidOperation, fields),
		Fields:   fields,
		Offset:   offset,
		Width:    width,
	}
}

func newInvalidSetterSignatureDiagnostic(offset int, width int, name string) diagnostic.Diagnostic {
	fields := map[string]fmt.Stringer{
		"name": diagnostic.Str(name),
	}
	return diagnostic.Diagnostic{
		Severity: diagnostic.Error,
		Code:     CodeInvalidSetterSignature,
		Message:  diagnostic.Render(diagnostic.DefaultLocale, CodeInvalidSetterSignature, fields),
		Fields:   fields,
		Offset:   offset,
		Width:    width,
	}
}

func newLambdaArityMismatchDiagnostic(offset int, width int, actual int, expected int) diagnostic.Diagnostic {
	fields := map[string]fmt.Stringer{
		"actual":   diagnostic.Int(actual),
		"expected": diagnostic.Int(expected),
	}
	return diagnostic.Diagnostic{
		Severity: diagnostic.Error,
		Code:     CodeLambdaArityMismatch,
		Message:  diagnostic.Render(diagnostic.DefaultLocale, CodeLambdaArityMismatch, fields),
		Fields:   fields,
		Offset:   offset,
		Width:    width,
	}
}

func newLoopVarImmutableDiagnostic(offset int, width int, name string) diagnostic.Diagnostic {
	fields := map[string]fmt.Stringer{
		"name": diagnostic.Str(name),
	}
	return diagnostic.Diagnostic{
		Severity: diagnostic.Error,
		Code:     CodeLoopVarImmutable,
		Message:  diagnostic.Render(diagnostic.DefaultLocale, CodeLoopVarImmutable, fields),
		Fields:   fields,
		Offset:   offset,
		Width:    width,
	}
}

func newMasterDuplicatePrimaryKeyDiagnostic(offset int, width int, key string, master string) diagnostic.Diagnostic {
	fields := map[string]fmt.Stringer{
		"key":    diagnostic.Str(key),
		"master": diagnostic.Str(master),
	}
	return diagnostic.Diagnostic{
		Severity: diagnostic.Error,
		Code:     CodeMasterDuplicatePrimaryKey,
		Message:  diagnostic.Render(diagnostic.DefaultLocale, CodeMasterDuplicatePrimaryKey, fields),
		Fields:   fields,
		Offset:   offset,
		Width:    width,
	}
}

func newMasterMissingPrimaryDiagnostic(offset int, width int, master string) diagnostic.Diagnostic {
	fields := map[string]fmt.Stringer{
		"master": diagnostic.Str(master),
	}
	return diagnostic.Diagnostic{
		Severity: diagnostic.Error,
		Code:     CodeMasterMissingPrimary,
		Message:  diagnostic.Render(diagnostic.DefaultLocale, CodeMasterMissingPrimary, fields),
		Fields:   fields,
		Offset:   offset,
		Width:    width,
	}
}

func newMasterMissingRowDiagnostic(offset int, width int, master string) diagnostic.Diagnostic {
	fields := map[string]fmt.Stringer{
		"master": diagnostic.Str(master),
	}
	return diagnostic.Diagnostic{
		Severity: diagnostic.Error,
		Code:     CodeMasterMissingRow,
		Message:  diagnostic.Render(diagnostic.DefaultLocale, CodeMasterMissingRow, fields),
		Fields:   fields,
		Offset:   offset,
		Width:    width,
	}
}

func newMasterPrimaryUnknownFieldDiagnostic(offset int, width int, key string, master string) diagnostic.Diagnostic {
	fields := map[string]fmt.Stringer{
		"key":    diagnostic.Str(key),
		"master": diagnostic.Str(master),
	}
	return diagnostic.Diagnostic{
		Severity: diagnostic.Error,
		Code:     CodeMasterPrimaryUnknownField,
		Message:  diagnostic.Render(diagnostic.DefaultLocale, CodeMasterPrimaryUnknownField, fields),
		Fields:   fields,
		Offset:   offset,
		Width:    width,
	}
}

func newMasterWhereUnsupportedDiagnostic(offset int, width int, master string) diagnostic.Diagnostic {
	fields := map[string]fmt.Stringer{
		"master": diagnostic.Str(master),
	}
	return diagnostic.Diagnostic{
		Severity: diagnostic.Error,
		Code:     CodeMasterWhereUnsupported,
		Message:  diagnostic.Render(diagnostic.DefaultLocale, CodeMasterWhereUnsupported, fields),
		Fields:   fields,
		Offset:   offset,
		Width:    width,
	}
}

func newMissingEffectDiagnostic(offset int, width int, fn string, effect string) diagnostic.Diagnostic {
	fields := map[string]fmt.Stringer{
		"fn":     diagnostic.Str(fn),
		"effect": diagnostic.Str(effect),
	}
	return diagnostic.Diagnostic{
		Severity: diagnostic.Error,
		Code:     CodeMissingEffect,
		Message:  diagnostic.Render(diagnostic.DefaultLocale, CodeMissingEffect, fields),
		Fields:   fields,
		Offset:   offset,
		Width:    width,
	}
}

func newMissingFieldDiagnostic(offset int, width int, field string, typ string) diagnostic.Diagnostic {
	fields := map[string]fmt.Stringer{
		"field": diagnostic.Str(field),
		"typ":   diagnostic.Str(typ),
	}
	return diagnostic.Diagnostic{
		Severity: diagnostic.Error,
		Code:     CodeMissingField,
		Message:  diagnostic.Render(diagnostic.DefaultLocale, CodeMissingField, fields),
		Fields:   fields,
		Offset:   offset,
		Width:    width,
	}
}

func newMissingInitializerDiagnostic(offset int, width int, name string) diagnostic.Diagnostic {
	fields := map[string]fmt.Stringer{
		"name": diagnostic.Str(name),
	}
	return diagnostic.Diagnostic{
		Severity: diagnostic.Error,
		Code:     CodeMissingInitializer,
		Message:  diagnostic.Render(diagnostic.DefaultLocale, CodeMissingInitializer, fields),
		Fields:   fields,
		Offset:   offset,
		Width:    width,
	}
}

func newMissingRequiredMethodDiagnostic(offset int, width int, typ string, iface string, method string) diagnostic.Diagnostic {
	fields := map[string]fmt.Stringer{
		"typ":    diagnostic.Str(typ),
		"iface":  diagnostic.Str(iface),
		"method": diagnostic.Str(method),
	}
	return diagnostic.Diagnostic{
		Severity: diagnostic.Error,
		Code:     CodeMissingRequiredMethod,
		Message:  diagnostic.Render(diagnostic.DefaultLocale, CodeMissingRequiredMethod, fields),
		Fields:   fields,
		Offset:   offset,
		Width:    width,
	}
}

func newMissingReturnDiagnostic(offset int, width int, name string) diagnostic.Diagnostic {
	fields := map[string]fmt.Stringer{
		"name": diagnostic.Str(name),
	}
	return diagnostic.Diagnostic{
		Severity: diagnostic.Error,
		Code:     CodeMissingReturn,
		Message:  diagnostic.Render(diagnostic.DefaultLocale, CodeMissingReturn, fields),
		Fields:   fields,
		Offset:   offset,
		Width:    width,
	}
}

func newNoMatchingFuncOverloadDiagnostic(offset int, width int, name string, types string) diagnostic.Diagnostic {
	fields := map[string]fmt.Stringer{
		"name":  diagnostic.Str(name),
		"types": diagnostic.Str(types),
	}
	return diagnostic.Diagnostic{
		Severity: diagnostic.Error,
		Code:     CodeNoMatchingFuncOverload,
		Message:  diagnostic.Render(diagnostic.DefaultLocale, CodeNoMatchingFuncOverload, fields),
		Fields:   fields,
		Offset:   offset,
		Width:    width,
	}
}

func newNoMatchingOverloadDiagnostic(offset int, width int, method string, types string) diagnostic.Diagnostic {
	fields := map[string]fmt.Stringer{
		"method": diagnostic.Str(method),
		"types":  diagnostic.Str(types),
	}
	return diagnostic.Diagnostic{
		Severity: diagnostic.Error,
		Code:     CodeNoMatchingOverload,
		Message:  diagnostic.Render(diagnostic.DefaultLocale, CodeNoMatchingOverload, fields),
		Fields:   fields,
		Offset:   offset,
		Width:    width,
	}
}

func newNoMethodOnUnboundedTypevarDiagnostic(offset int, width int, method string) diagnostic.Diagnostic {
	fields := map[string]fmt.Stringer{
		"method": diagnostic.Str(method),
	}
	return diagnostic.Diagnostic{
		Severity: diagnostic.Error,
		Code:     CodeNoMethodOnUnboundedTypevar,
		Message:  diagnostic.Render(diagnostic.DefaultLocale, CodeNoMethodOnUnboundedTypevar, fields),
		Fields:   fields,
		Offset:   offset,
		Width:    width,
	}
}

func newNonExhaustiveMatchDiagnostic(offset int, width int, typ string, missing string) diagnostic.Diagnostic {
	fields := map[string]fmt.Stringer{
		"typ":     diagnostic.Str(typ),
		"missing": diagnostic.Str(missing),
	}
	return diagnostic.Diagnostic{
		Severity: diagnostic.Error,
		Code:     CodeNonExhaustiveMatch,
		Message:  diagnostic.Render(diagnostic.DefaultLocale, CodeNonExhaustiveMatch, fields),
		Fields:   fields,
		Offset:   offset,
		Width:    width,
	}
}

func newNonExhaustiveSwitchDiagnostic(offset int, width int, typ string, missing string) diagnostic.Diagnostic {
	fields := map[string]fmt.Stringer{
		"typ":     diagnostic.Str(typ),
		"missing": diagnostic.Str(missing),
	}
	return diagnostic.Diagnostic{
		Severity: diagnostic.Error,
		Code:     CodeNonExhaustiveSwitch,
		Message:  diagnostic.Render(diagnostic.DefaultLocale, CodeNonExhaustiveSwitch, fields),
		Fields:   fields,
		Offset:   offset,
		Width:    width,
	}
}

func newNotARecordDiagnostic(offset int, width int, typ string) diagnostic.Diagnostic {
	fields := map[string]fmt.Stringer{
		"typ": diagnostic.Str(typ),
	}
	return diagnostic.Diagnostic{
		Severity: diagnostic.Error,
		Code:     CodeNotARecord,
		Message:  diagnostic.Render(diagnostic.DefaultLocale, CodeNotARecord, fields),
		Fields:   fields,
		Offset:   offset,
		Width:    width,
	}
}

func newNotAnInterfaceDiagnostic(offset int, width int, name string) diagnostic.Diagnostic {
	fields := map[string]fmt.Stringer{
		"name": diagnostic.Str(name),
	}
	return diagnostic.Diagnostic{
		Severity: diagnostic.Error,
		Code:     CodeNotAnInterface,
		Message:  diagnostic.Render(diagnostic.DefaultLocale, CodeNotAnInterface, fields),
		Fields:   fields,
		Offset:   offset,
		Width:    width,
	}
}

func newNotExportedDiagnostic(offset int, width int, name string, path string) diagnostic.Diagnostic {
	fields := map[string]fmt.Stringer{
		"name": diagnostic.Str(name),
		"path": diagnostic.Str(path),
	}
	return diagnostic.Diagnostic{
		Severity: diagnostic.Error,
		Code:     CodeNotExported,
		Message:  diagnostic.Render(diagnostic.DefaultLocale, CodeNotExported, fields),
		Fields:   fields,
		Offset:   offset,
		Width:    width,
	}
}

func newNotIterableDiagnostic(offset int, width int, typ string) diagnostic.Diagnostic {
	fields := map[string]fmt.Stringer{
		"typ": diagnostic.Str(typ),
	}
	return diagnostic.Diagnostic{
		Severity: diagnostic.Error,
		Code:     CodeNotIterable,
		Message:  diagnostic.Render(diagnostic.DefaultLocale, CodeNotIterable, fields),
		Fields:   fields,
		Offset:   offset,
		Width:    width,
	}
}

func newRangeStepZeroDiagnostic(offset int, width int) diagnostic.Diagnostic {
	return diagnostic.Diagnostic{
		Severity: diagnostic.Error,
		Code:     CodeRangeStepZero,
		Message:  diagnostic.Render(diagnostic.DefaultLocale, CodeRangeStepZero, nil),
		Fields:   nil,
		Offset:   offset,
		Width:    width,
	}
}

func newRefinementNotBoolDiagnostic(offset int, width int, typ string) diagnostic.Diagnostic {
	fields := map[string]fmt.Stringer{
		"typ": diagnostic.Str(typ),
	}
	return diagnostic.Diagnostic{
		Severity: diagnostic.Error,
		Code:     CodeRefinementNotBool,
		Message:  diagnostic.Render(diagnostic.DefaultLocale, CodeRefinementNotBool, fields),
		Fields:   fields,
		Offset:   offset,
		Width:    width,
	}
}

func newRefinementNotConstantDiagnostic(offset int, width int) diagnostic.Diagnostic {
	return diagnostic.Diagnostic{
		Severity: diagnostic.Error,
		Code:     CodeRefinementNotConstant,
		Message:  diagnostic.Render(diagnostic.DefaultLocale, CodeRefinementNotConstant, nil),
		Fields:   nil,
		Offset:   offset,
		Width:    width,
	}
}

func newRefinementViolationDiagnostic(offset int, width int, value string, typ string, predicate string, diagram string) diagnostic.Diagnostic {
	fields := map[string]fmt.Stringer{
		"value":     diagnostic.Str(value),
		"typ":       diagnostic.Str(typ),
		"predicate": diagnostic.Str(predicate),
		"diagram":   diagnostic.Str(diagram),
	}
	return diagnostic.Diagnostic{
		Severity: diagnostic.Error,
		Code:     CodeRefinementViolation,
		Message:  diagnostic.Render(diagnostic.DefaultLocale, CodeRefinementViolation, fields),
		Fields:   fields,
		Offset:   offset,
		Width:    width,
	}
}

func newScrutineeNotComparableDiagnostic(offset int, width int, typ string) diagnostic.Diagnostic {
	fields := map[string]fmt.Stringer{
		"typ": diagnostic.Str(typ),
	}
	return diagnostic.Diagnostic{
		Severity: diagnostic.Error,
		Code:     CodeScrutineeNotComparable,
		Message:  diagnostic.Render(diagnostic.DefaultLocale, CodeScrutineeNotComparable, fields),
		Fields:   fields,
		Offset:   offset,
		Width:    width,
	}
}

func newSelfOutsideMethodDiagnostic(offset int, width int) diagnostic.Diagnostic {
	return diagnostic.Diagnostic{
		Severity: diagnostic.Error,
		Code:     CodeSelfOutsideMethod,
		Message:  diagnostic.Render(diagnostic.DefaultLocale, CodeSelfOutsideMethod, nil),
		Fields:   nil,
		Offset:   offset,
		Width:    width,
	}
}

func newStaticCollisionDiagnostic(offset int, width int, name string, typ string) diagnostic.Diagnostic {
	fields := map[string]fmt.Stringer{
		"name": diagnostic.Str(name),
		"typ":  diagnostic.Str(typ),
	}
	return diagnostic.Diagnostic{
		Severity: diagnostic.Error,
		Code:     CodeStaticCollision,
		Message:  diagnostic.Render(diagnostic.DefaultLocale, CodeStaticCollision, fields),
		Fields:   fields,
		Offset:   offset,
		Width:    width,
	}
}

func newTernaryBranchMismatchDiagnostic(offset int, width int, then string, els string) diagnostic.Diagnostic {
	fields := map[string]fmt.Stringer{
		"then": diagnostic.Str(then),
		"els":  diagnostic.Str(els),
	}
	return diagnostic.Diagnostic{
		Severity: diagnostic.Error,
		Code:     CodeTernaryBranchMismatch,
		Message:  diagnostic.Render(diagnostic.DefaultLocale, CodeTernaryBranchMismatch, fields),
		Fields:   fields,
		Offset:   offset,
		Width:    width,
	}
}

func newTernaryConditionNotBoolDiagnostic(offset int, width int, typ string) diagnostic.Diagnostic {
	fields := map[string]fmt.Stringer{
		"typ": diagnostic.Str(typ),
	}
	return diagnostic.Diagnostic{
		Severity: diagnostic.Error,
		Code:     CodeTernaryConditionNotBool,
		Message:  diagnostic.Render(diagnostic.DefaultLocale, CodeTernaryConditionNotBool, fields),
		Fields:   fields,
		Offset:   offset,
		Width:    width,
	}
}

func newTypeMismatchDiagnostic(offset int, width int, actual string, expected string) diagnostic.Diagnostic {
	fields := map[string]fmt.Stringer{
		"actual":   diagnostic.Str(actual),
		"expected": diagnostic.Str(expected),
	}
	return diagnostic.Diagnostic{
		Severity: diagnostic.Error,
		Code:     CodeTypeMismatch,
		Message:  diagnostic.Render(diagnostic.DefaultLocale, CodeTypeMismatch, fields),
		Fields:   fields,
		Offset:   offset,
		Width:    width,
	}
}

func newUndefinedNameDiagnostic(offset int, width int, name string) diagnostic.Diagnostic {
	fields := map[string]fmt.Stringer{
		"name": diagnostic.Str(name),
	}
	return diagnostic.Diagnostic{
		Severity: diagnostic.Error,
		Code:     CodeUndefinedName,
		Message:  diagnostic.Render(diagnostic.DefaultLocale, CodeUndefinedName, fields),
		Fields:   fields,
		Offset:   offset,
		Width:    width,
	}
}

func newUnfoldedConstDiagnostic(offset int, width int, name string, reason string) diagnostic.Diagnostic {
	fields := map[string]fmt.Stringer{
		"name":   diagnostic.Str(name),
		"reason": diagnostic.Str(reason),
	}
	return diagnostic.Diagnostic{
		Severity: diagnostic.Error,
		Code:     CodeUnfoldedConst,
		Message:  diagnostic.Render(diagnostic.DefaultLocale, CodeUnfoldedConst, fields),
		Fields:   fields,
		Offset:   offset,
		Width:    width,
	}
}

func newUninferableCollectionDiagnostic(offset int, width int) diagnostic.Diagnostic {
	return diagnostic.Diagnostic{
		Severity: diagnostic.Error,
		Code:     CodeUninferableCollection,
		Message:  diagnostic.Render(diagnostic.DefaultLocale, CodeUninferableCollection, nil),
		Fields:   nil,
		Offset:   offset,
		Width:    width,
	}
}

func newUninferableParameterDiagnostic(offset int, width int, name string) diagnostic.Diagnostic {
	fields := map[string]fmt.Stringer{
		"name": diagnostic.Str(name),
	}
	return diagnostic.Diagnostic{
		Severity: diagnostic.Error,
		Code:     CodeUninferableParameter,
		Message:  diagnostic.Render(diagnostic.DefaultLocale, CodeUninferableParameter, fields),
		Fields:   fields,
		Offset:   offset,
		Width:    width,
	}
}

func newUninferableRecordDiagnostic(offset int, width int) diagnostic.Diagnostic {
	return diagnostic.Diagnostic{
		Severity: diagnostic.Error,
		Code:     CodeUninferableRecord,
		Message:  diagnostic.Render(diagnostic.DefaultLocale, CodeUninferableRecord, nil),
		Fields:   nil,
		Offset:   offset,
		Width:    width,
	}
}

func newUninferableResultDiagnostic(offset int, width int) diagnostic.Diagnostic {
	return diagnostic.Diagnostic{
		Severity: diagnostic.Error,
		Code:     CodeUninferableResult,
		Message:  diagnostic.Render(diagnostic.DefaultLocale, CodeUninferableResult, nil),
		Fields:   nil,
		Offset:   offset,
		Width:    width,
	}
}

func newUninferableTypeParamDiagnostic(offset int, width int, name string) diagnostic.Diagnostic {
	fields := map[string]fmt.Stringer{
		"name": diagnostic.Str(name),
	}
	return diagnostic.Diagnostic{
		Severity: diagnostic.Error,
		Code:     CodeUninferableTypeParam,
		Message:  diagnostic.Render(diagnostic.DefaultLocale, CodeUninferableTypeParam, fields),
		Fields:   fields,
		Offset:   offset,
		Width:    width,
	}
}

func newUnknownAssociatedConstDiagnostic(offset int, width int, typ string, name string) diagnostic.Diagnostic {
	fields := map[string]fmt.Stringer{
		"typ":  diagnostic.Str(typ),
		"name": diagnostic.Str(name),
	}
	return diagnostic.Diagnostic{
		Severity: diagnostic.Error,
		Code:     CodeUnknownAssociatedConst,
		Message:  diagnostic.Render(diagnostic.DefaultLocale, CodeUnknownAssociatedConst, fields),
		Fields:   fields,
		Offset:   offset,
		Width:    width,
	}
}

func newUnknownEnumMemberDiagnostic(offset int, width int, enum string, member string) diagnostic.Diagnostic {
	fields := map[string]fmt.Stringer{
		"enum":   diagnostic.Str(enum),
		"member": diagnostic.Str(member),
	}
	return diagnostic.Diagnostic{
		Severity: diagnostic.Error,
		Code:     CodeUnknownEnumMember,
		Message:  diagnostic.Render(diagnostic.DefaultLocale, CodeUnknownEnumMember, fields),
		Fields:   fields,
		Offset:   offset,
		Width:    width,
	}
}

func newUnknownFieldDiagnostic(offset int, width int, field string, typ string) diagnostic.Diagnostic {
	fields := map[string]fmt.Stringer{
		"field": diagnostic.Str(field),
		"typ":   diagnostic.Str(typ),
	}
	return diagnostic.Diagnostic{
		Severity: diagnostic.Error,
		Code:     CodeUnknownField,
		Message:  diagnostic.Render(diagnostic.DefaultLocale, CodeUnknownField, fields),
		Fields:   fields,
		Offset:   offset,
		Width:    width,
	}
}

func newUnknownMemberDiagnostic(offset int, width int, name string, namespace string) diagnostic.Diagnostic {
	fields := map[string]fmt.Stringer{
		"name":      diagnostic.Str(name),
		"namespace": diagnostic.Str(namespace),
	}
	return diagnostic.Diagnostic{
		Severity: diagnostic.Error,
		Code:     CodeUnknownMember,
		Message:  diagnostic.Render(diagnostic.DefaultLocale, CodeUnknownMember, fields),
		Fields:   fields,
		Offset:   offset,
		Width:    width,
	}
}

func newUnknownStaticDiagnostic(offset int, width int, name string, typ string) diagnostic.Diagnostic {
	fields := map[string]fmt.Stringer{
		"name": diagnostic.Str(name),
		"typ":  diagnostic.Str(typ),
	}
	return diagnostic.Diagnostic{
		Severity: diagnostic.Error,
		Code:     CodeUnknownStatic,
		Message:  diagnostic.Render(diagnostic.DefaultLocale, CodeUnknownStatic, fields),
		Fields:   fields,
		Offset:   offset,
		Width:    width,
	}
}

func newUnknownTypeDiagnostic(offset int, width int, name string) diagnostic.Diagnostic {
	fields := map[string]fmt.Stringer{
		"name": diagnostic.Str(name),
	}
	return diagnostic.Diagnostic{
		Severity: diagnostic.Error,
		Code:     CodeUnknownType,
		Message:  diagnostic.Render(diagnostic.DefaultLocale, CodeUnknownType, fields),
		Fields:   fields,
		Offset:   offset,
		Width:    width,
	}
}

func newUnreachableArmDiagnostic(offset int, width int) diagnostic.Diagnostic {
	return diagnostic.Diagnostic{
		Severity: diagnostic.Error,
		Code:     CodeUnreachableArm,
		Message:  diagnostic.Render(diagnostic.DefaultLocale, CodeUnreachableArm, nil),
		Fields:   nil,
		Offset:   offset,
		Width:    width,
	}
}

func newUnusedEffectDiagnostic(offset int, width int, fn string, effect string) diagnostic.Diagnostic {
	fields := map[string]fmt.Stringer{
		"fn":     diagnostic.Str(fn),
		"effect": diagnostic.Str(effect),
	}
	return diagnostic.Diagnostic{
		Severity: diagnostic.Warning,
		Code:     CodeUnusedEffect,
		Message:  diagnostic.Render(diagnostic.DefaultLocale, CodeUnusedEffect, fields),
		Fields:   fields,
		Offset:   offset,
		Width:    width,
	}
}

func newUseNotFoundDiagnostic(offset int, width int, path string) diagnostic.Diagnostic {
	fields := map[string]fmt.Stringer{
		"path": diagnostic.Str(path),
	}
	return diagnostic.Diagnostic{
		Severity: diagnostic.Error,
		Code:     CodeUseNotFound,
		Message:  diagnostic.Render(diagnostic.DefaultLocale, CodeUseNotFound, fields),
		Fields:   fields,
		Offset:   offset,
		Width:    width,
	}
}
