// Code generated by "go generate"; DO NOT EDIT.

package diagnostic

import "fmt"

// renderers maps each diagnostic code to a function that renders its message
// in a given locale from the diagnostic's fields.
var renderers = map[Code]func(Locale, map[string]fmt.Stringer) string{
	"masterbelt.lexer.invalid_datetime": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return "不正な日時リテラル: " + f["text"].String()
		default:
			return "invalid datetime literal: " + f["text"].String()
		}
	},
	"masterbelt.lexer.invalid_escape": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return "不正なエスケープシーケンス: " + f["escape"].String()
		default:
			return "invalid escape sequence: " + f["escape"].String()
		}
	},
	"masterbelt.lexer.invalid_unicode_escape": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return "不正なUnicodeエスケープ: " + f["escape"].String()
		default:
			return "invalid unicode escape: " + f["escape"].String()
		}
	},
	"masterbelt.lexer.unexpected_character": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return "予期しない文字: " + f["char"].String()
		default:
			return "unexpected character: " + f["char"].String()
		}
	},
	"masterbelt.lexer.unknown_duration_unit": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return "未知の期間単位: " + f["unit"].String()
		default:
			return "unknown duration unit: " + f["unit"].String()
		}
	},
	"masterbelt.lexer.unterminated_block_comment": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return "ブロックコメントが閉じられていません"
		default:
			return "unterminated block comment"
		}
	},
	"masterbelt.lexer.unterminated_string": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return "文字列リテラルが閉じられていません"
		default:
			return "unterminated string literal"
		}
	},
	"masterbelt.parser.concrete.arrow_block_body": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return "'->' の後には式が必要です。ブロック本体にするには '->' を削除してください"
		default:
			return "expected expression after '->'; remove '->' to use a block body"
		}
	},
	"masterbelt.parser.concrete.expected_assign": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return "'=' が必要です"
		default:
			return "expected '='"
		}
	},
	"masterbelt.parser.concrete.expected_const": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return "'const' が必要です"
		default:
			return "expected 'const'"
		}
	},
	"masterbelt.parser.concrete.expected_expression": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return "式が必要です"
		default:
			return "expected expression"
		}
	},
	"masterbelt.parser.concrete.expected_from": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return "'from' が必要です"
		default:
			return "expected 'from'"
		}
	},
	"masterbelt.parser.concrete.expected_func_body": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return "'->' か '{' が必要です"
		default:
			return "expected '->' or '{'"
		}
	},
	"masterbelt.parser.concrete.expected_identifier": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return "識別子が必要です"
		default:
			return "expected identifier"
		}
	},
	"masterbelt.parser.concrete.expected_operand": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return "'" + f["operator"].String() + "' の後にオペランドが必要です"
		default:
			return "expected operand after '" + f["operator"].String() + "'"
		}
	},
	"masterbelt.parser.concrete.expected_param_list": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return "'(' が必要です"
		default:
			return "expected '('"
		}
	},
	"masterbelt.parser.concrete.expected_path": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return "インポートパスの文字列が必要です"
		default:
			return "expected import path string"
		}
	},
	"masterbelt.parser.concrete.expected_type": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return "型が必要です"
		default:
			return "expected type"
		}
	},
	"masterbelt.parser.concrete.unexpected_token": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return "予期しないトークン: " + f["kind"].String()
		default:
			return "unexpected token: " + f["kind"].String()
		}
	},
	"masterbelt.semantic.ambiguous_func_overload": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return "関数 " + f["name"].String() + " の呼び出しが曖昧です: " + f["types"].String() + " に複数のオーバーロードが適合します"
		default:
			return "ambiguous call: more than one overload of function " + f["name"].String() + " accepts " + f["types"].String()
		}
	},
	"masterbelt.semantic.ambiguous_import": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return f["name"].String() + " は曖昧です。複数のインポートから到来しています"
		default:
			return f["name"].String() + " is ambiguous; it arrives from more than one import"
		}
	},
	"masterbelt.semantic.ambiguous_overload": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return "メソッド " + f["method"].String() + " の呼び出しが曖昧です: " + f["types"].String() + " に複数のオーバーロードが適合します"
		default:
			return "ambiguous call: more than one overload of method " + f["method"].String() + " accepts " + f["types"].String()
		}
	},
	"masterbelt.semantic.arity_mismatch": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return "関数 " + f["name"].String() + " は引数を " + f["expected"].String() + " 個取りますが、" + f["actual"].String() + " 個が渡されています"
		default:
			return "function " + f["name"].String() + " takes " + f["expected"].String() + " argument(s); " + f["actual"].String() + " given"
		}
	},
	"masterbelt.semantic.arm_value_type_mismatch": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return f["actual"].String() + " を " + f["expected"].String() + " の switch 値として使用できません"
		default:
			return "cannot use " + f["actual"].String() + " as a " + f["expected"].String() + " switch value"
		}
	},
	"masterbelt.semantic.assertion_failed": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return "表明が成立しません: " + f["cond"].String() + f["doc"].String() + f["diagram"].String()
		default:
			return "assertion failed: " + f["cond"].String() + f["doc"].String() + f["diagram"].String()
		}
	},
	"masterbelt.semantic.assertion_not_bool": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return "表明は bool でなければなりません(" + f["typ"].String() + ")"
		default:
			return "assertion must be a bool; got " + f["typ"].String()
		}
	},
	"masterbelt.semantic.assertion_not_constant": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return "表明はコンパイル時定数ではありません"
		default:
			return "assertion is not a compile-time constant"
		}
	},
	"masterbelt.semantic.condition_not_bool": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return "if の条件は bool でなければなりません(" + f["typ"].String() + ")"
		default:
			return "if condition must be a bool; got " + f["typ"].String()
		}
	},
	"masterbelt.semantic.constant_overflow": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return "定数 " + f["value"].String() + " は " + f["typ"].String() + " に収まりません"
		default:
			return "constant " + f["value"].String() + " overflows " + f["typ"].String()
		}
	},
	"masterbelt.semantic.cyclic_module": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return f["path"].String() + " を経由するインポートサイクルです"
		default:
			return "import cycle through " + f["path"].String()
		}
	},
	"masterbelt.semantic.cyclic_reference": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return f["name"].String() + " を含む循環参照です"
		default:
			return "cyclic reference involving " + f["name"].String()
		}
	},
	"masterbelt.semantic.division_by_zero": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return "ゼロ除算です"
		default:
			return "division by zero"
		}
	},
	"masterbelt.semantic.duplicate_declaration": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return f["name"].String() + " が重複して宣言されています"
		default:
			return "duplicate declaration of " + f["name"].String()
		}
	},
	"masterbelt.semantic.duplicate_enum_member": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return "enum メンバ " + f["name"].String() + " が重複しています"
		default:
			return "duplicate enum member " + f["name"].String()
		}
	},
	"masterbelt.semantic.duplicate_enum_value": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return "enum メンバ " + f["name"].String() + " は値 " + f["value"].String() + " を重複させています"
		default:
			return "enum member " + f["name"].String() + " duplicates the value " + f["value"].String()
		}
	},
	"masterbelt.semantic.duplicate_func_overload": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return "関数 " + f["name"].String() + " が同じ引数型 (" + f["types"].String() + ") で再宣言されています"
		default:
			return "function " + f["name"].String() + " redeclares the parameter types (" + f["types"].String() + ")"
		}
	},
	"masterbelt.semantic.duplicate_overload": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return "メソッド " + f["method"].String() + " が同じ引数型 (" + f["types"].String() + ") で再宣言されています"
		default:
			return "method " + f["method"].String() + " redeclares the parameter types (" + f["types"].String() + ")"
		}
	},
	"masterbelt.semantic.duplicate_switch_arm": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return "switch の arm が重複しています: " + f["value"].String()
		default:
			return "duplicate switch arm for " + f["value"].String()
		}
	},
	"masterbelt.semantic.effect_in_pure_context": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return f["context"].String() + " はコンパイル時に評価されるため pure である必要があります。effect " + f["effect"].String() + " は使用できません"
		default:
			return "a " + f["context"].String() + " is evaluated at compile time and must be pure; effect " + f["effect"].String() + " is not allowed"
		}
	},
	"masterbelt.semantic.invalid_enum_base_type": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return f["typ"].String() + " は enum の基底型に使えません(整数型か string を指定してください)"
		default:
			return f["typ"].String() + " is not a valid enum base type (use an integer type or string)"
		}
	},
	"masterbelt.semantic.invalid_operation": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return "メソッド " + f["method"].String() + " を " + f["types"].String() + " に適用できません"
		default:
			return "cannot apply method " + f["method"].String() + " to " + f["types"].String()
		}
	},
	"masterbelt.semantic.lambda_arity_mismatch": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return "関数リテラルのパラメータが " + f["actual"].String() + " 個ありますが、" + f["expected"].String() + " 個が必要です"
		default:
			return "function literal has " + f["actual"].String() + " parameters; " + f["expected"].String() + " expected"
		}
	},
	"masterbelt.semantic.missing_effect": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return "関数 " + f["fn"].String() + " は effect " + f["effect"].String() + " を宣言せずに使用しています"
		default:
			return "function " + f["fn"].String() + " uses effect " + f["effect"].String() + " without declaring it"
		}
	},
	"masterbelt.semantic.missing_field": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return f["typ"].String() + " のレコードリテラルにフィールド " + f["field"].String() + " がありません"
		default:
			return "record literal of " + f["typ"].String() + " is missing field " + f["field"].String()
		}
	},
	"masterbelt.semantic.missing_return": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return "関数 " + f["name"].String() + " が値を返しません"
		default:
			return "function " + f["name"].String() + " never returns a value"
		}
	},
	"masterbelt.semantic.no_bound": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return f["typ"].String() + " は範囲を持たないため " + f["name"].String() + " はありません"
		default:
			return f["typ"].String() + " has no bound and so no " + f["name"].String()
		}
	},
	"masterbelt.semantic.no_matching_func_overload": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return "関数 " + f["name"].String() + " のどのオーバーロードも " + f["types"].String() + " に適合しません"
		default:
			return "no overload of function " + f["name"].String() + " accepts " + f["types"].String()
		}
	},
	"masterbelt.semantic.no_matching_overload": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return "メソッド " + f["method"].String() + " のどのオーバーロードも " + f["types"].String() + " に適合しません"
		default:
			return "no overload of method " + f["method"].String() + " accepts " + f["types"].String()
		}
	},
	"masterbelt.semantic.non_exhaustive_switch": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return f["typ"].String() + " の switch が網羅的ではありません: " + f["missing"].String()
		default:
			return "switch on " + f["typ"].String() + " is not exhaustive: " + f["missing"].String()
		}
	},
	"masterbelt.semantic.not_a_record": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return f["typ"].String() + " はレコード型ではありません"
		default:
			return f["typ"].String() + " is not a record type"
		}
	},
	"masterbelt.semantic.not_exported": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return f["path"].String() + " は " + f["name"].String() + " を公開していません"
		default:
			return f["path"].String() + " does not export " + f["name"].String()
		}
	},
	"masterbelt.semantic.refinement_not_bool": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return "where 節は bool でなければなりません(" + f["typ"].String() + ")"
		default:
			return "where clause must be a bool; got " + f["typ"].String()
		}
	},
	"masterbelt.semantic.refinement_not_constant": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return "where 節はコンパイル時に評価できる述語ではありません"
		default:
			return "where clause is not a compile-time predicate"
		}
	},
	"masterbelt.semantic.refinement_violation": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return "値 " + f["value"].String() + " は " + f["typ"].String() + " の制約を満たしません: " + f["predicate"].String() + f["diagram"].String()
		default:
			return "value " + f["value"].String() + " does not satisfy " + f["typ"].String() + ": " + f["predicate"].String() + f["diagram"].String()
		}
	},
	"masterbelt.semantic.self_outside_method": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return "self はメソッド本体の中でのみ使えます"
		default:
			return "self is only available inside a method body"
		}
	},
	"masterbelt.semantic.ternary_branch_mismatch": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return "三項演算子の両枝の型が一致しません: " + f["then"].String() + " と " + f["els"].String()
		default:
			return "ternary branches have mismatched types: " + f["then"].String() + " and " + f["els"].String()
		}
	},
	"masterbelt.semantic.ternary_condition_not_bool": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return "三項演算子の条件は bool でなければなりません(" + f["typ"].String() + ")"
		default:
			return "ternary condition must be a bool; got " + f["typ"].String()
		}
	},
	"masterbelt.semantic.type_mismatch": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return f["actual"].String() + " を " + f["expected"].String() + " として使えません"
		default:
			return "cannot use " + f["actual"].String() + " as " + f["expected"].String()
		}
	},
	"masterbelt.semantic.undefined_name": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return "未定義の名前: " + f["name"].String()
		default:
			return "undefined name: " + f["name"].String()
		}
	},
	"masterbelt.semantic.uninferable_collection": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return "このコレクションリテラルの型を推論できません。型注釈を付けてください"
		default:
			return "cannot infer the type of this collection literal; annotate it"
		}
	},
	"masterbelt.semantic.uninferable_parameter": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return "パラメータ " + f["name"].String() + " の型を推論できません。型注釈を付けてください"
		default:
			return "cannot infer the type of parameter " + f["name"].String() + "; annotate it"
		}
	},
	"masterbelt.semantic.uninferable_record": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return "このレコードリテラルの型を推論できません。型名を付けるか型注釈を付けてください"
		default:
			return "cannot infer the type of this record literal; name its type or annotate it"
		}
	},
	"masterbelt.semantic.uninferable_result": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return "この関数リテラルの結果型を推論できません。注釈を付けるか値を返してください"
		default:
			return "cannot infer this function literal's result type; annotate it or return a value"
		}
	},
	"masterbelt.semantic.unknown_associated_const": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return f["typ"].String() + " に関連定数 " + f["name"].String() + " はありません"
		default:
			return f["typ"].String() + " has no associated constant " + f["name"].String()
		}
	},
	"masterbelt.semantic.unknown_enum_member": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return f["enum"].String() + " にメンバ " + f["member"].String() + " はありません"
		default:
			return f["enum"].String() + " has no member " + f["member"].String()
		}
	},
	"masterbelt.semantic.unknown_field": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return f["typ"].String() + " にフィールド " + f["field"].String() + " はありません"
		default:
			return f["typ"].String() + " has no field " + f["field"].String()
		}
	},
	"masterbelt.semantic.unknown_member": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return f["namespace"].String() + " に公開メンバ " + f["name"].String() + " はありません"
		default:
			return f["namespace"].String() + " has no exported member " + f["name"].String()
		}
	},
	"masterbelt.semantic.unknown_type": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return "未知の型: " + f["name"].String()
		default:
			return "unknown type: " + f["name"].String()
		}
	},
	"masterbelt.semantic.unreachable_arm": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return "到達不能な arm です。先行する arm かワイルドカードがすべての値に一致します"
		default:
			return "unreachable arm: a previous arm or the wildcard already matches every value"
		}
	},
	"masterbelt.semantic.unused_effect": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return "関数 " + f["fn"].String() + " は effect " + f["effect"].String() + " を宣言していますが使用していません"
		default:
			return "function " + f["fn"].String() + " declares effect " + f["effect"].String() + " but never uses it"
		}
	},
	"masterbelt.semantic.use_not_found": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return "インポートするファイルが見つかりません: " + f["path"].String()
		default:
			return "imported file not found: " + f["path"].String()
		}
	},
	"project.config.entry_not_found": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return "エントリファイルが見つかりません: " + f["path"].String()
		default:
			return "entry file not found: " + f["path"].String()
		}
	},
	"project.config.invalid": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return "不正な masterbelt.toml: " + f["detail"].String()
		default:
			return "invalid masterbelt.toml: " + f["detail"].String()
		}
	},
	"project.config.missing": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return "masterbelt.toml がこのディレクトリにも親ディレクトリにも見つかりません"
		default:
			return "masterbelt.toml not found in this directory or any parent"
		}
	},
	"project.config.missing_entry": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return "masterbelt.toml に entry が指定されていません"
		default:
			return "masterbelt.toml does not set entry"
		}
	},
	"project.config.profile_entry_not_found": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return "プロファイル " + f["profile"].String() + " のエントリファイルが見つかりません: " + f["path"].String()
		default:
			return "entry file not found for profile " + f["profile"].String() + ": " + f["path"].String()
		}
	},
	"project.config.profile_missing_entry": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return "プロファイル " + f["profile"].String() + " に entry が指定されていません"
		default:
			return "profile " + f["profile"].String() + " does not set entry"
		}
	},
	"project.config.unknown_profile": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return "プロファイル " + f["profile"].String() + " は masterbelt.toml に定義されていません"
		default:
			return "profile " + f["profile"].String() + " is not defined in masterbelt.toml"
		}
	},
}
