// Code generated by "go generate"; DO NOT EDIT.

package diagnostic

import "fmt"

// renderers maps each diagnostic code to a function that renders its message
// in a given locale from the diagnostic's fields.
var renderers = map[Code]func(Locale, map[string]fmt.Stringer) string{
	"belt.lexer.invalid_datetime": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return "不正な日時リテラル: " + f["text"].String()
		default:
			return "invalid datetime literal: " + f["text"].String()
		}
	},
	"belt.lexer.invalid_escape": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return "不正なエスケープシーケンス: " + f["escape"].String()
		default:
			return "invalid escape sequence: " + f["escape"].String()
		}
	},
	"belt.lexer.invalid_unicode_escape": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return "不正なUnicodeエスケープ: " + f["escape"].String()
		default:
			return "invalid unicode escape: " + f["escape"].String()
		}
	},
	"belt.lexer.unexpected_character": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return "予期しない文字: " + f["char"].String()
		default:
			return "unexpected character: " + f["char"].String()
		}
	},
	"belt.lexer.unknown_duration_unit": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return "未知の期間単位: " + f["unit"].String()
		default:
			return "unknown duration unit: " + f["unit"].String()
		}
	},
	"belt.lexer.unterminated_block_comment": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return "ブロックコメントが閉じられていません"
		default:
			return "unterminated block comment"
		}
	},
	"belt.lexer.unterminated_string": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return "文字列リテラルが閉じられていません"
		default:
			return "unterminated string literal"
		}
	},
	"belt.lint.unreachable_code": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return "到達できないコード"
		default:
			return "unreachable code"
		}
	},
	"belt.lint.unused_declaration": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return f["name"].String() + " は使われていません"
		default:
			return f["name"].String() + " is never used"
		}
	},
	"belt.parser.concrete.arrow_block_body": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return "'->' の後には式が必要です。ブロック本体にするには '->' を削除してください"
		default:
			return "expected expression after '->'; remove '->' to use a block body"
		}
	},
	"belt.parser.concrete.expected_assign": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return "'=' が必要です"
		default:
			return "expected '='"
		}
	},
	"belt.parser.concrete.expected_const": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return "'const' が必要です"
		default:
			return "expected 'const'"
		}
	},
	"belt.parser.concrete.expected_expression": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return "式が必要です"
		default:
			return "expected expression"
		}
	},
	"belt.parser.concrete.expected_fn": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return "'static' の後には 'fn' が必要です"
		default:
			return "expected 'fn' after 'static'"
		}
	},
	"belt.parser.concrete.expected_from": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return "'from' が必要です"
		default:
			return "expected 'from'"
		}
	},
	"belt.parser.concrete.expected_func_body": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return "'->' か '{' が必要です"
		default:
			return "expected '->' or '{'"
		}
	},
	"belt.parser.concrete.expected_identifier": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return "識別子が必要です"
		default:
			return "expected identifier"
		}
	},
	"belt.parser.concrete.expected_operand": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return "'" + f["operator"].String() + "' の後にオペランドが必要です"
		default:
			return "expected operand after '" + f["operator"].String() + "'"
		}
	},
	"belt.parser.concrete.expected_param_list": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return "'(' が必要です"
		default:
			return "expected '('"
		}
	},
	"belt.parser.concrete.expected_path": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return "インポートパスの文字列が必要です"
		default:
			return "expected import path string"
		}
	},
	"belt.parser.concrete.expected_type": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return "型が必要です"
		default:
			return "expected type"
		}
	},
	"belt.parser.concrete.unexpected_token": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return "予期しないトークン: " + f["kind"].String()
		default:
			return "unexpected token: " + f["kind"].String()
		}
	},
	"belt.semantic.accessor_collision": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return "アクセサ " + f["name"].String() + " は " + f["typ"].String() + " の同名の別メンバと衝突しています"
		default:
			return "accessor " + f["name"].String() + " collides with another member of the same name on " + f["typ"].String()
		}
	},
	"belt.semantic.ambiguous_func_overload": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return "関数 " + f["name"].String() + " の呼び出しが曖昧です: " + f["types"].String() + " に複数のオーバーロードが適合します"
		default:
			return "ambiguous call: more than one overload of function " + f["name"].String() + " accepts " + f["types"].String()
		}
	},
	"belt.semantic.ambiguous_import": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return f["name"].String() + " は曖昧です。複数のインポートから到来しています"
		default:
			return f["name"].String() + " is ambiguous; it arrives from more than one import"
		}
	},
	"belt.semantic.ambiguous_overload": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return "メソッド " + f["method"].String() + " の呼び出しが曖昧です: " + f["types"].String() + " に複数のオーバーロードが適合します"
		default:
			return "ambiguous call: more than one overload of method " + f["method"].String() + " accepts " + f["types"].String()
		}
	},
	"belt.semantic.ambiguous_union_member": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return f["actual"].String() + " が " + f["typ"].String() + " のどのメンバとして流入するか確定できません。short(1) のような明示変換で確定させてください"
		default:
			return "cannot tell which member of " + f["typ"].String() + " " + f["actual"].String() + " flows in as; pin it with an explicit conversion (e.g. short(1))"
		}
	},
	"belt.semantic.arity_mismatch": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return "関数 " + f["name"].String() + " は引数を " + f["expected"].String() + " 個取りますが、" + f["actual"].String() + " 個が渡されています"
		default:
			return "function " + f["name"].String() + " takes " + f["expected"].String() + " argument(s); " + f["actual"].String() + " given"
		}
	},
	"belt.semantic.arm_type_not_in_union": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return f["arm"].String() + " は " + f["typ"].String() + " のメンバではありません"
		default:
			return f["arm"].String() + " is not a member of " + f["typ"].String()
		}
	},
	"belt.semantic.arm_value_type_mismatch": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return f["actual"].String() + " を " + f["expected"].String() + " の switch 値として使用できません"
		default:
			return "cannot use " + f["actual"].String() + " as a " + f["expected"].String() + " switch value"
		}
	},
	"belt.semantic.assertion_failed": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return "表明が成立しません: " + f["cond"].String() + f["doc"].String() + f["diagram"].String()
		default:
			return "assertion failed: " + f["cond"].String() + f["doc"].String() + f["diagram"].String()
		}
	},
	"belt.semantic.assertion_not_bool": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return "表明は bool でなければなりません(" + f["typ"].String() + ")"
		default:
			return "assertion must be a bool; got " + f["typ"].String()
		}
	},
	"belt.semantic.assertion_not_constant": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return "表明はコンパイル時定数ではありません"
		default:
			return "assertion is not a compile-time constant"
		}
	},
	"belt.semantic.assign_to_const": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return f["name"].String() + " には代入できません。const は不変です。可変なローカルには let を使ってください"
		default:
			return "cannot assign to " + f["name"].String() + ": a const is immutable; use let for a mutable local"
		}
	},
	"belt.semantic.assign_to_undefined": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return f["name"].String() + " には代入できません。その名前の let 束縛がスコープにありません"
		default:
			return "cannot assign to " + f["name"].String() + ": no let binding with that name is in scope"
		}
	},
	"belt.semantic.assign_type_mismatch": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return f["name"].String() + " に " + f["actual"].String() + " を代入できません。型は " + f["expected"].String() + " に固定されています"
		default:
			return "cannot assign " + f["actual"].String() + " to " + f["name"].String() + ": its type is fixed to " + f["expected"].String()
		}
	},
	"belt.semantic.bound_not_satisfied": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return f["typ"].String() + " は境界 " + f["bound"].String() + " を満たしません: その interface を実装していません"
		default:
			return f["typ"].String() + " does not satisfy the bound " + f["bound"].String() + ": it does not implement that interface"
		}
	},
	"belt.semantic.builtin_outside_builtin": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return "= builtin は builtin サーフェス専用です。registry は " + f["name"].String() + " の実体を供給しません"
		default:
			return "= builtin is reserved for the builtin surface; the registry supplies no native for " + f["name"].String()
		}
	},
	"belt.semantic.condition_not_bool": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return "if の条件は bool でなければなりません(" + f["typ"].String() + ")"
		default:
			return "if condition must be a bool; got " + f["typ"].String()
		}
	},
	"belt.semantic.constant_overflow": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return "定数 " + f["value"].String() + " は " + f["typ"].String() + " に収まりません"
		default:
			return "constant " + f["value"].String() + " overflows " + f["typ"].String()
		}
	},
	"belt.semantic.cyclic_module": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return f["path"].String() + " を経由するインポートサイクルです"
		default:
			return "import cycle through " + f["path"].String()
		}
	},
	"belt.semantic.cyclic_reference": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return f["name"].String() + " を含む循環参照です"
		default:
			return "cyclic reference involving " + f["name"].String()
		}
	},
	"belt.semantic.cyclic_type_projection": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return f["typ"].String() + " の " + f["member"].String() + " の型射影が循環しており、地となる具体型がありません"
		default:
			return "the type projection of " + f["member"].String() + " on " + f["typ"].String() + " is cyclic with no grounding type"
		}
	},
	"belt.semantic.division_by_zero": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return "ゼロ除算です"
		default:
			return "division by zero"
		}
	},
	"belt.semantic.duplicate_declaration": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return f["name"].String() + " が重複して宣言されています"
		default:
			return "duplicate declaration of " + f["name"].String()
		}
	},
	"belt.semantic.duplicate_enum_member": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return "enum メンバ " + f["name"].String() + " が重複しています"
		default:
			return "duplicate enum member " + f["name"].String()
		}
	},
	"belt.semantic.duplicate_enum_value": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return "enum メンバ " + f["name"].String() + " は値 " + f["value"].String() + " を重複させています"
		default:
			return "enum member " + f["name"].String() + " duplicates the value " + f["value"].String()
		}
	},
	"belt.semantic.duplicate_func_overload": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return "関数 " + f["name"].String() + " が同じ引数型 (" + f["types"].String() + ") で再宣言されています"
		default:
			return "function " + f["name"].String() + " redeclares the parameter types (" + f["types"].String() + ")"
		}
	},
	"belt.semantic.duplicate_match_arm": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return "match の arm が重複しています: " + f["arm"].String()
		default:
			return "duplicate match arm for " + f["arm"].String()
		}
	},
	"belt.semantic.duplicate_overload": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return "メソッド " + f["method"].String() + " が同じ引数型 (" + f["types"].String() + ") で再宣言されています"
		default:
			return "method " + f["method"].String() + " redeclares the parameter types (" + f["types"].String() + ")"
		}
	},
	"belt.semantic.duplicate_switch_arm": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return "switch の arm が重複しています: " + f["value"].String()
		default:
			return "duplicate switch arm for " + f["value"].String()
		}
	},
	"belt.semantic.effect_in_pure_context": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return f["context"].String() + " はコンパイル時に評価されるため pure である必要があります。effect " + f["effect"].String() + " は使用できません"
		default:
			return "a " + f["context"].String() + " is evaluated at compile time and must be pure; effect " + f["effect"].String() + " is not allowed"
		}
	},
	"belt.semantic.extern_outside_builtin": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return "extern は builtin サーフェス専用です。ここで " + f["name"].String() + " の実体を供給する仕組みはありません"
		default:
			return "extern is reserved for the builtin surface; nothing here can supply a native for " + f["name"].String()
		}
	},
	"belt.semantic.generic_static": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return "ジェネリックな static fn " + f["name"].String() + " はサポートされていません"
		default:
			return "generic static fn " + f["name"].String() + " is not supported"
		}
	},
	"belt.semantic.generic_type_projection": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return "ジェネリック型 " + f["typ"].String() + " のフィールド射影はまだサポートされていません"
		default:
			return "projecting a field off the generic type " + f["typ"].String() + " is not supported yet"
		}
	},
	"belt.semantic.immutable_data": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return "フィールドや要素には代入できません。データは不変です。新しい値を作ってください"
		default:
			return "cannot assign to a field or element: data is immutable; build a new value instead"
		}
	},
	"belt.semantic.index_out_of_range": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return "インデックス " + f["index"].String() + " は長さ " + f["length"].String() + " のリストの範囲外です"
		default:
			return "index " + f["index"].String() + " is out of range for a list of length " + f["length"].String()
		}
	},
	"belt.semantic.interface_member_conflict": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return f["child"].String() + " は無関係な 2 つの interface (" + f["first"].String() + " と " + f["second"].String() + ") から " + f["method"].String() + " を継承しています"
		default:
			return f["child"].String() + " inherits " + f["method"].String() + " from two unrelated interfaces (" + f["first"].String() + " and " + f["second"].String() + ")"
		}
	},
	"belt.semantic.interface_member_override": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return f["child"].String() + " は " + f["method"].String() + " を再宣言できません: すでに " + f["ancestor"].String() + " から継承しています"
		default:
			return f["child"].String() + " cannot redeclare " + f["method"].String() + ": it is already inherited from " + f["ancestor"].String()
		}
	},
	"belt.semantic.invalid_enum_base_type": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return f["typ"].String() + " は enum の基底型に使えません(整数型か string を指定してください)"
		default:
			return f["typ"].String() + " is not a valid enum base type (use an integer type or string)"
		}
	},
	"belt.semantic.invalid_getter_signature": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return "ゲッター " + f["name"].String() + " は引数を取れません"
		default:
			return "getter " + f["name"].String() + " must take no parameters"
		}
	},
	"belt.semantic.invalid_operation": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return "メソッド " + f["method"].String() + " を " + f["types"].String() + " に適用できません"
		default:
			return "cannot apply method " + f["method"].String() + " to " + f["types"].String()
		}
	},
	"belt.semantic.invalid_setter_signature": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return "セッター " + f["name"].String() + " は引数を 1 つ取り self を返す必要があります"
		default:
			return "setter " + f["name"].String() + " must take one parameter and return self"
		}
	},
	"belt.semantic.lambda_arity_mismatch": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return "関数リテラルのパラメータが " + f["actual"].String() + " 個ありますが、" + f["expected"].String() + " 個が必要です"
		default:
			return "function literal has " + f["actual"].String() + " parameters; " + f["expected"].String() + " expected"
		}
	},
	"belt.semantic.loop_var_immutable": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return "ループ変数 " + f["name"].String() + " には代入できません。不変です。蓄積には let を使ってください"
		default:
			return "cannot assign to the loop variable " + f["name"].String() + ": it is immutable; accumulate into a let"
		}
	},
	"belt.semantic.master_duplicate_primary_key": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return "master " + f["master"].String() + " は primary キー列 " + f["key"].String() + " を重複させています"
		default:
			return "master " + f["master"].String() + " repeats primary-key column " + f["key"].String()
		}
	},
	"belt.semantic.master_missing_primary": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return "master " + f["master"].String() + " に primary キーがありません"
		default:
			return "master " + f["master"].String() + " has no primary key"
		}
	},
	"belt.semantic.master_missing_row": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return "master " + f["master"].String() + " に行レコードがありません"
		default:
			return "master " + f["master"].String() + " has no row record"
		}
	},
	"belt.semantic.master_primary_unknown_field": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return "master " + f["master"].String() + " に primary キー " + f["key"].String() + " のフィールドがありません"
		default:
			return "master " + f["master"].String() + " has no field " + f["key"].String() + " named by its primary key"
		}
	},
	"belt.semantic.master_where_unsupported": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return "master " + f["master"].String() + " の行述語(where)はまだサポートされていません"
		default:
			return "master " + f["master"].String() + " does not support a row predicate (where) yet"
		}
	},
	"belt.semantic.member_is_not_a_type": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return f["typ"].String() + "." + f["member"].String() + " は値であり型ではないため、型位置には置けません"
		default:
			return f["typ"].String() + "." + f["member"].String() + " is a value and not a type so it cannot be used in type position"
		}
	},
	"belt.semantic.missing_effect": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return "関数 " + f["fn"].String() + " は effect " + f["effect"].String() + " を宣言せずに使用しています"
		default:
			return "function " + f["fn"].String() + " uses effect " + f["effect"].String() + " without declaring it"
		}
	},
	"belt.semantic.missing_field": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return f["typ"].String() + " のレコードリテラルにフィールド " + f["field"].String() + " がありません"
		default:
			return "record literal of " + f["typ"].String() + " is missing field " + f["field"].String()
		}
	},
	"belt.semantic.missing_initializer": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return "let " + f["name"].String() + " は初期化が必要です。let " + f["name"].String() + " = 値 と書いてください"
		default:
			return "let " + f["name"].String() + " must be initialized: write let " + f["name"].String() + " = value"
		}
	},
	"belt.semantic.missing_readable_member": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return f["typ"].String() + " は " + f["iface"].String() + " を実装していません: 読める member " + f["member"].String() + ": " + f["want"].String() + " がありません"
		default:
			return f["typ"].String() + " does not implement " + f["iface"].String() + ": missing readable member " + f["member"].String() + ": " + f["want"].String()
		}
	},
	"belt.semantic.missing_required_method": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return f["typ"].String() + " は " + f["iface"].String() + " を実装していません: 必須メソッド " + f["method"].String() + " がありません"
		default:
			return f["typ"].String() + " does not implement " + f["iface"].String() + ": missing required method " + f["method"].String()
		}
	},
	"belt.semantic.missing_return": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return "関数 " + f["name"].String() + " が値を返しません"
		default:
			return "function " + f["name"].String() + " never returns a value"
		}
	},
	"belt.semantic.no_matching_func_overload": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return "関数 " + f["name"].String() + " のどのオーバーロードも " + f["types"].String() + " に適合しません"
		default:
			return "no overload of function " + f["name"].String() + " accepts " + f["types"].String()
		}
	},
	"belt.semantic.no_matching_overload": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return "メソッド " + f["method"].String() + " のどのオーバーロードも " + f["types"].String() + " に適合しません"
		default:
			return "no overload of method " + f["method"].String() + " accepts " + f["types"].String()
		}
	},
	"belt.semantic.no_method_on_unbounded_typevar": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return "無境界の型パラメータに対して " + f["method"].String() + " は呼べません。メソッドを使うには interface 境界を付けてください"
		default:
			return "cannot call " + f["method"].String() + " on an unbounded type parameter: add an interface bound to call its methods"
		}
	},
	"belt.semantic.non_exhaustive_match": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return f["typ"].String() + " の match が網羅的ではありません: " + f["missing"].String()
		default:
			return "match on " + f["typ"].String() + " is not exhaustive: " + f["missing"].String()
		}
	},
	"belt.semantic.non_exhaustive_switch": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return f["typ"].String() + " の switch が網羅的ではありません: " + f["missing"].String()
		default:
			return "switch on " + f["typ"].String() + " is not exhaustive: " + f["missing"].String()
		}
	},
	"belt.semantic.not_a_record": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return f["typ"].String() + " はレコード型ではありません"
		default:
			return f["typ"].String() + " is not a record type"
		}
	},
	"belt.semantic.not_an_interface": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return f["name"].String() + " は interface ではありません"
		default:
			return f["name"].String() + " is not an interface"
		}
	},
	"belt.semantic.not_exported": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return f["path"].String() + " は " + f["name"].String() + " を公開していません"
		default:
			return f["path"].String() + " does not export " + f["name"].String()
		}
	},
	"belt.semantic.not_iterable": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return "for で反復できるのは foldable なコレクションだけです。" + f["typ"].String() + " は foldable ではありません"
		default:
			return "for can only iterate a foldable collection; " + f["typ"].String() + " is not foldable"
		}
	},
	"belt.semantic.range_step_zero": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return "range のステップに 0 は指定できません"
		default:
			return "range step cannot be zero"
		}
	},
	"belt.semantic.refinement_not_bool": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return "where 節は bool でなければなりません(" + f["typ"].String() + ")"
		default:
			return "where clause must be a bool; got " + f["typ"].String()
		}
	},
	"belt.semantic.refinement_not_constant": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return "where 節はコンパイル時に評価できる述語ではありません"
		default:
			return "where clause is not a compile-time predicate"
		}
	},
	"belt.semantic.refinement_violation": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return "値 " + f["value"].String() + " は " + f["typ"].String() + " の制約を満たしません: " + f["predicate"].String() + f["diagram"].String()
		default:
			return "value " + f["value"].String() + " does not satisfy " + f["typ"].String() + ": " + f["predicate"].String() + f["diagram"].String()
		}
	},
	"belt.semantic.scrutinee_not_comparable": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return "switch の対象は comparable が必要です (" + f["typ"].String() + ")。record や union を型で分岐するには match を使ってください"
		default:
			return "switch needs a comparable scrutinee (" + f["typ"].String() + "); use match to branch on a record or union type"
		}
	},
	"belt.semantic.self_outside_method": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return "self はメソッド本体の中でのみ使えます"
		default:
			return "self is only available inside a method body"
		}
	},
	"belt.semantic.static_collision": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return "static fn " + f["name"].String() + " は " + f["typ"].String() + " の同名の関連定数か enum メンバと衝突しています"
		default:
			return "static fn " + f["name"].String() + " collides with an associated constant or enum member of the same name on " + f["typ"].String()
		}
	},
	"belt.semantic.ternary_branch_mismatch": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return "三項演算子の両枝の型が一致しません: " + f["then"].String() + " と " + f["els"].String()
		default:
			return "ternary branches have mismatched types: " + f["then"].String() + " and " + f["els"].String()
		}
	},
	"belt.semantic.ternary_condition_not_bool": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return "三項演算子の条件は bool でなければなりません(" + f["typ"].String() + ")"
		default:
			return "ternary condition must be a bool; got " + f["typ"].String()
		}
	},
	"belt.semantic.type_arity_mismatch": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return "型 " + f["name"].String() + " は型引数を " + f["expected"].String() + " 個取りますが、" + f["actual"].String() + " 個が渡されています"
		default:
			return "type " + f["name"].String() + " takes " + f["expected"].String() + " type argument(s); " + f["actual"].String() + " given"
		}
	},
	"belt.semantic.type_has_no_fields": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return f["typ"].String() + " には射影できるフィールドがありません (" + f["member"].String() + ")"
		default:
			return f["typ"].String() + " has no fields to project " + f["member"].String() + " from"
		}
	},
	"belt.semantic.type_in_value_position": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return "型はコンパイル時の値であり、値スロットには格納できません。型エイリアス (type X = ...) を使ってください"
		default:
			return "a type is a compile-time value and cannot be stored in a value slot; use a type alias (type X = ...) instead"
		}
	},
	"belt.semantic.type_mismatch": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return f["actual"].String() + " を " + f["expected"].String() + " として使えません"
		default:
			return "cannot use " + f["actual"].String() + " as " + f["expected"].String()
		}
	},
	"belt.semantic.undefined_name": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return "未定義の名前: " + f["name"].String()
		default:
			return "undefined name: " + f["name"].String()
		}
	},
	"belt.semantic.unfolded_const": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return "定数 " + f["name"].String() + " はコンパイル時値に畳めませんでした: " + f["reason"].String() + " — depth は評価予算の超過です(計算を浅くするか分割してください)。evaluator gap は masterbelt のバグです(報告してください)"
		default:
			return "constant " + f["name"].String() + " has no compile-time value: " + f["reason"].String() + " — depth means the computation exceeded the evaluation budget (make it shallower or split it); evaluator gap means this is a masterbelt bug (please report it)"
		}
	},
	"belt.semantic.uninferable_collection": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return "このコレクションリテラルの型を推論できません。型注釈を付けてください"
		default:
			return "cannot infer the type of this collection literal; annotate it"
		}
	},
	"belt.semantic.uninferable_parameter": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return "パラメータ " + f["name"].String() + " の型を推論できません。型注釈を付けてください"
		default:
			return "cannot infer the type of parameter " + f["name"].String() + "; annotate it"
		}
	},
	"belt.semantic.uninferable_record": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return "このレコードリテラルの型を推論できません。型名を付けるか型注釈を付けてください"
		default:
			return "cannot infer the type of this record literal; name its type or annotate it"
		}
	},
	"belt.semantic.uninferable_result": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return "この関数リテラルの結果型を推論できません。注釈を付けるか値を返してください"
		default:
			return "cannot infer this function literal's result type; annotate it or return a value"
		}
	},
	"belt.semantic.uninferable_type_param": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return "型パラメータ " + f["name"].String() + " を引数から推論できません。引数で決まるようにしてください"
		default:
			return "cannot infer the type parameter " + f["name"].String() + " from the arguments; no argument pins it"
		}
	},
	"belt.semantic.unknown_associated_const": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return f["typ"].String() + " に関連定数 " + f["name"].String() + " はありません"
		default:
			return f["typ"].String() + " has no associated constant " + f["name"].String()
		}
	},
	"belt.semantic.unknown_enum_member": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return f["enum"].String() + " にメンバ " + f["member"].String() + " はありません"
		default:
			return f["enum"].String() + " has no member " + f["member"].String()
		}
	},
	"belt.semantic.unknown_field": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return f["typ"].String() + " にフィールド " + f["field"].String() + " はありません"
		default:
			return f["typ"].String() + " has no field " + f["field"].String()
		}
	},
	"belt.semantic.unknown_member": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return f["namespace"].String() + " に公開メンバ " + f["name"].String() + " はありません"
		default:
			return f["namespace"].String() + " has no exported member " + f["name"].String()
		}
	},
	"belt.semantic.unknown_static": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return f["typ"].String() + " に static fn " + f["name"].String() + " はありません"
		default:
			return f["typ"].String() + " has no static fn " + f["name"].String()
		}
	},
	"belt.semantic.unknown_type": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return "未知の型: " + f["name"].String()
		default:
			return "unknown type: " + f["name"].String()
		}
	},
	"belt.semantic.unreachable_arm": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return "到達不能な arm です。先行する arm かワイルドカードがすべての値に一致します"
		default:
			return "unreachable arm: a previous arm or the wildcard already matches every value"
		}
	},
	"belt.semantic.unused_effect": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return "関数 " + f["fn"].String() + " は effect " + f["effect"].String() + " を宣言していますが使用していません"
		default:
			return "function " + f["fn"].String() + " declares effect " + f["effect"].String() + " but never uses it"
		}
	},
	"belt.semantic.use_not_found": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return "インポートするファイルが見つかりません: " + f["path"].String()
		default:
			return "imported file not found: " + f["path"].String()
		}
	},
	"project.config.entry_not_found": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return "エントリファイルが見つかりません: " + f["path"].String()
		default:
			return "entry file not found: " + f["path"].String()
		}
	},
	"project.config.invalid": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return "不正な masterbelt.toml: " + f["detail"].String()
		default:
			return "invalid masterbelt.toml: " + f["detail"].String()
		}
	},
	"project.config.missing": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return "masterbelt.toml がこのディレクトリにも親ディレクトリにも見つかりません"
		default:
			return "masterbelt.toml not found in this directory or any parent"
		}
	},
	"project.config.missing_entry": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return "masterbelt.toml に entry が指定されていません"
		default:
			return "masterbelt.toml does not set entry"
		}
	},
	"project.config.profile_entry_not_found": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return "プロファイル " + f["profile"].String() + " のエントリファイルが見つかりません: " + f["path"].String()
		default:
			return "entry file not found for profile " + f["profile"].String() + ": " + f["path"].String()
		}
	},
	"project.config.profile_missing_entry": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return "プロファイル " + f["profile"].String() + " に entry が指定されていません"
		default:
			return "profile " + f["profile"].String() + " does not set entry"
		}
	},
	"project.config.unknown_profile": func(loc Locale, f map[string]fmt.Stringer) string {
		switch loc {
		case "ja":
			return "プロファイル " + f["profile"].String() + " は masterbelt.toml に定義されていません"
		default:
			return "profile " + f["profile"].String() + " is not defined in masterbelt.toml"
		}
	},
}
