// Code generated by "go generate"; DO NOT EDIT.

package lexer

import (
	"fmt"

	"github.com/masterbelt/masterbelt/pkg/diagnostic"
)

const (
	CodeInvalidDatetime          diagnostic.Code = "belt.lexer.invalid_datetime"
	CodeInvalidEscape            diagnostic.Code = "belt.lexer.invalid_escape"
	CodeInvalidUnicodeEscape     diagnostic.Code = "belt.lexer.invalid_unicode_escape"
	CodeUnexpectedCharacter      diagnostic.Code = "belt.lexer.unexpected_character"
	CodeUnknownDurationUnit      diagnostic.Code = "belt.lexer.unknown_duration_unit"
	CodeUnterminatedBlockComment diagnostic.Code = "belt.lexer.unterminated_block_comment"
	CodeUnterminatedString       diagnostic.Code = "belt.lexer.unterminated_string"
)

func newInvalidDatetimeDiagnostic(offset int, width int, text string) diagnostic.Diagnostic {
	fields := map[string]fmt.Stringer{
		"text": diagnostic.Str(text),
	}
	return diagnostic.Diagnostic{
		Severity: diagnostic.Error,
		Code:     CodeInvalidDatetime,
		Message:  diagnostic.Render(diagnostic.DefaultLocale, CodeInvalidDatetime, fields),
		Fields:   fields,
		Offset:   offset,
		Width:    width,
	}
}

func newInvalidEscapeDiagnostic(offset int, width int, escape string) diagnostic.Diagnostic {
	fields := map[string]fmt.Stringer{
		"escape": diagnostic.Str(escape),
	}
	return diagnostic.Diagnostic{
		Severity: diagnostic.Error,
		Code:     CodeInvalidEscape,
		Message:  diagnostic.Render(diagnostic.DefaultLocale, CodeInvalidEscape, fields),
		Fields:   fields,
		Offset:   offset,
		Width:    width,
	}
}

func newInvalidUnicodeEscapeDiagnostic(offset int, width int, escape string) diagnostic.Diagnostic {
	fields := map[string]fmt.Stringer{
		"escape": diagnostic.Str(escape),
	}
	return diagnostic.Diagnostic{
		Severity: diagnostic.Error,
		Code:     CodeInvalidUnicodeEscape,
		Message:  diagnostic.Render(diagnostic.DefaultLocale, CodeInvalidUnicodeEscape, fields),
		Fields:   fields,
		Offset:   offset,
		Width:    width,
	}
}

func newUnexpectedCharacterDiagnostic(offset int, width int, char rune) diagnostic.Diagnostic {
	fields := map[string]fmt.Stringer{
		"char": diagnostic.Rune(char),
	}
	return diagnostic.Diagnostic{
		Severity: diagnostic.Error,
		Code:     CodeUnexpectedCharacter,
		Message:  diagnostic.Render(diagnostic.DefaultLocale, CodeUnexpectedCharacter, fields),
		Fields:   fields,
		Offset:   offset,
		Width:    width,
	}
}

func newUnknownDurationUnitDiagnostic(offset int, width int, unit string) diagnostic.Diagnostic {
	fields := map[string]fmt.Stringer{
		"unit": diagnostic.Str(unit),
	}
	return diagnostic.Diagnostic{
		Severity: diagnostic.Error,
		Code:     CodeUnknownDurationUnit,
		Message:  diagnostic.Render(diagnostic.DefaultLocale, CodeUnknownDurationUnit, fields),
		Fields:   fields,
		Offset:   offset,
		Width:    width,
	}
}

func newUnterminatedBlockCommentDiagnostic(offset int, width int) diagnostic.Diagnostic {
	return diagnostic.Diagnostic{
		Severity: diagnostic.Error,
		Code:     CodeUnterminatedBlockComment,
		Message:  diagnostic.Render(diagnostic.DefaultLocale, CodeUnterminatedBlockComment, nil),
		Fields:   nil,
		Offset:   offset,
		Width:    width,
	}
}

func newUnterminatedStringDiagnostic(offset int, width int) diagnostic.Diagnostic {
	return diagnostic.Diagnostic{
		Severity: diagnostic.Error,
		Code:     CodeUnterminatedString,
		Message:  diagnostic.Render(diagnostic.DefaultLocale, CodeUnterminatedString, nil),
		Fields:   nil,
		Offset:   offset,
		Width:    width,
	}
}
